Kaggle/docker-python

Dockerfile

MPLD3 is a cool library that brings interactive matplotlib to python. I think it must be on Kaggle.
Check http://mpld3.github.io/ for details.

Attempt to add mpld3 package

---

Dockerfile

This PR adds two lines to the `Dockerfile`:
- `pip install altair`
- `jupyter nbextension install --py vega` to activate the Vega extension. This makes it possible to display Vega charts in the Jupyter notebook.
[Altair](https://altair-viz.github.io/) is a Python frontend for [Vega-Lite](https://vega.github.io/vega-lite/), and it integrates with Pandas out of the box. Its declarative syntax makes it very easy to create complex charts and that's why I'm proposing its addition.

Add Altair package

---

Dockerfile

adding https://pypi.python.org/pypi/ImageHash
checked that after pip install in the image one can import imagehash

ImageHash library

---

Dockerfile

adding SimpleITK for processing and handling DICOM volumes (addressing issue https://github.com/Kaggle/docker-python/issues/57) and required for the tutorial for the DSB (https://github.com/booz-allen-hamilton/DSB3Tutorial)

Adding SimpleITK Conda Package

---

Dockerfile

Add `fbprophet` as package installed in Kaggle Docker image. More info on Prophet, which was open-sourced last week: https://facebookincubator.github.io/prophet/

Update Dockerfile with Facebook Prophet

---

Dockerfile

This adds a new package for performing fast joins based on string similarity. The package is well-tested and maintained by the researchers in University of Wisconsin-Madison. Here is a link to their [project](https://sites.google.com/site/anhaidgroup/projects/magellan/py_stringsimjoin).

Add the py_stringsimjoin package

---

Dockerfile

"Spectral Python (SPy) is a pure Python module for processing hyperspectral image data."
It's very useful for viewing multispectral data that doesn't look like "normal" rgb images with standard 8-bit values.
Very simple dependencies: numpy, pillow and matplotlib (all already installed)
http://www.spectralpython.net/installation.html

add spectral library for multi/hyper spectral images

---

Dockerfile
patches/tornado-fix-issue-2097.patch

This adds a generic patching mechanism to `kaggle/python` and a single patch
to apply the equivalent of https://github.com/tornadoweb/tornado/pull/2098 so
we don't have to wait for the upstream change to trickle down.
Resulting image has been verified to prevent kaggle websockets to be broken off
every 100s.

Patch tornado for .NET websocket compatibility.

---

Dockerfile

Add the Python library `paramnb` to Dockerfile. To enable running [a notebook](https://github.com/bokeh/datashader/blob/master/examples/nyc_taxi-paramnb.ipynb) relating to interactive visualization for NYC Taxi with datashader.

add paramnb

---

Dockerfile

DIPY is a python package used for brain image analysis such as MRI data (2D and 3D). Would be really useful for many competitions.

dipy package

---

Dockerfile

Here's a glimpse of what it does, highly dynamic at the moment, changing/adding stuff on a daily basis: https://github.com/dvaida/hallucinate/blob/master/Teaser.ipynb BTW, the reason I submitted this as a pull request is a 'reverse engineering' kernel (that I cannot run w/o hallucinate) on the Titanic Survivors proving some realistic scores on the dataset, how you can get almost 83% on the pub LB but still with a 79 - 80% score on the "real" dataset - hence the reverse engineering part, I used it to learn/validate the training scores and show how the LB can be misleading rather than submit a 1. accuracy score ;-)

Add hallucinate - a lightweight library for quick ML experimentation

---

Dockerfile

pip install nibabel
the nibabel library supports reading and writing of neuroimaging data formats.

pip install nibabel

---

Dockerfile

Koko is a light-weight tool for extracting patterns from text. The previous build of Koko could not be included in Kaggle Docker as it used Spacy1.9.0. The current version is compatible with Spacy 2.0.2 (which is running on Kaggle). Many thanks for considering this.

Adding the pykoko package

---

Dockerfile

There are many datasets in the [physionet physiobank database](https://www.physionet.org/physiobank/) with physiologic signals and related data for use by the biomedical research community.
Some data has already been uploaded to kaggle data sets but it's hard to use because it is not in the right format:
https://www.kaggle.com/ecerulm/apneaecg/discussion/33856
By adding the [wfdb](https://www.physionet.org/physiotools/wfdb.shtml) package to the kernels it will allow users to explore this data set and more. There are lots of really interesting machine learning challenges in these data sets.
Fixes #163

Add wfdb to pip install

---

Dockerfile
test_build.py

This unpins mxnet version. It was build from source before, and then moved to pip install in 6c4cac180ced8b0712e3cd3b34adac19f6daaa46.
I verified that package is installed correctly by building the docker image locally. Here is the relevant part of the build log where the package is installed:
```
Collecting mxnet
Downloading mxnet-1.0.0.post4-py2.py3-none-manylinux1_x86_64.whl (27.4MB)
Requirement already satisfied: requests==2.18.4 in /opt/conda/lib/python3.6/site-packages (from mxnet)
Collecting graphviz==0.8.1 (from mxnet)
Downloading graphviz-0.8.1-py2.py3-none-any.whl
Requirement already satisfied: numpy<=1.13.3 in /opt/conda/lib/python3.6/site-packages (from mxnet)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from …
```

Unpin MxNet

---

Dockerfile

This is more of a question than a recommendation.  According to [the PyTorch homepage](http://pytorch.org), it looks like it's now recommended to install PyTorch from the conda channel `pytorch`, rather than `soumith`:
And if we compare the channel versions, it looks like [`soumith/pytorch` is on v0.2](https://anaconda.org/soumith/pytorch) and was [last updated 4-5 months ago](https://anaconda.org/soumith/pytorch/files), whereas [`pytorch/pytorch` is on v0.3](https://anaconda.org/pytorch/pytorch) and was [last updated 1-2 months ago](https://anaconda.org/pytorch/pytorch/files).
I'm not sure of any official stance on this, other than the project homepage, and I also don't have enough background with this repo to know why it's currently using `soumith`, but it does appear to be an outdated …

Update PyTorch conda channel from `soumith` to `pytorch`?

---

Dockerfile

Adding yellowbrick to the dockerfile so that folks on kaggle can use this library.
From our documentation at http://www.scikit-yb.org/en/latest/:
> Yellowbrick is a suite of visual diagnostic tools called “Visualizers” that extend the Scikit-Learn API to allow human steering of the model selection process. In a nutshell, Yellowbrick combines Scikit-Learn with Matplotlib in the best tradition of the Scikit-Learn documentation, but to produce visualizations for your models!

Add yellowbrick: a machine learning visualization library

---

Dockerfile

Ktext uses threading based parallelism for common deep-learning NLP preprocessing steps.
This is for a project with @hamelsmu

Add ktext for fast text processing with Keras

---

patches/sitecustomize.py
test_build.py

This patch will allow Kaggle users to use PyTorch and fast.ai once again. They are currently broken in kernels due to an underlying problem with Torch's treatment of static TLS, documented in https://github.com/pytorch/pytorch/issues/2575. Our users have reported the issue in https://github.com/Kaggle/docker-python/issues/157 and https://github.com/Kaggle/docker-python/issues/166.

Workaround for PyTorch issue 2575

---

Dockerfile

[Featuretools](www.featuretools.com) is a library for feature engineering that is compatible with pandas and sklearn. It can be found on [github](https://github.com/featuretools/featuretools).
This is a follow up from #154 where a version requirement was overwriting numpy. As discussed with @nerdcha we have relaxed that requirement which seems to resolve the issue. I've also added a 
`pip install pympler` and `pip install s3fs` following the conversation there. The full output from the install can be found below.
```
Status: Downloaded newer image for kaggle/python:latest
root@215a35d7f988:/# pip install pympler
Collecting pympler
Downloading Pympler-0.5.tar.gz (170kB)
100% |████████████████████████████████| 174kB 2.2MB/s 
Building wheels for collected packages: pympler
Running setup.py …
```

pip install featuretools

---

Dockerfile
test_build.py

I checked that it installed with `pip install shap` and loaded correctly with `import shap` on the latest docker image. This package explains the output of any machine learning model, but with a fast implementation integrated with XGBoost, LightGBM, and scikit-learn tree models (see https://github.com/slundberg/shap). It was requested a while back to make an example Kaggle notebook available, so this PR is to make that possible.

Add shap to Dockerfile

---

Dockerfile

Adding vowpal wabbit build from github. This follows #135. The sequence of `build` and `test` succeeds.

add vw build

---

Jenkinsfile

The new ephemeral workers are using an image with all the dependencies setup properly.
This solves the connectivity issue with the debian repo.

Use ephemeral workers

---

Dockerfile
patches/kaggle_bashrc

Create a directory for pip to install modules via users' "pip install" command.
Set up PIP_CONFIG_FILE & PYTHONPATH to use those modeuls in a Kernel session.
Currently this change is no-op until we populate KAGGLE_WORKING_DIR from the worker.

Patch .bashrc to set up pip to enable pip install

---

README.md
kaggle_tools_update.Dockerfile
test_build.py

The community team needs the latest version of Learn Tools in order to launch new learn content. 
In order to unblock them quickly, I created a new docker file that build a new image with the latest learntools package from the latest stable.
This is a temporary workaround and hopefully, we will be back soon to a state where we can simply build a new image with all the latest dependencies.
I also added a test to confirm that learntools works as expected. Output from the test run
```
Tensorflow ok
Using TensorFlow backend.
Keras ok
Correct: What?! You got it right without needing a hint or anything? Drats. Well hey, you should still continue to the next step to get some practice asking for a hint and checking solutions. (Even though you obviously don't need any help here.)
learntools ok
... …
```

Learn tools quick update

---

build

We are not using the latest image from anaconda so :latest != to our pinned base image in the FROM command. This means we pull an image we don't end up using. With `--pull`, we ensure we pull the latest image that matches the version specified in the docker FROM command.

Improve build script by using the --pull flag

---

Dockerfile

installing tensorpack from master was breaking the build. 
The latest version of tensorpack published was on August 10th 2018 (12 days ago).

Install tensorpack using pip

---

Dockerfile

pytorch installs the gpu version by default now unless we use the cpu package explicitly.
The build was failing with the following error:
```
Aug 23 23:25:17 [0m[91mTraceback (most recent call last):
Aug 23 23:25:17   File "setup.py", line 4, in <module>
Aug 23 23:25:17     from torch.utils.cpp_extension import BuildExtension, CppExtension
Aug 23 23:25:17   File "/opt/conda/lib/python3.6/site-packages/torch/__init__.py", line 80, in <module>
Aug 23 23:25:17     from torch._C import *
Aug 23 23:25:17 ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory
```

Install pytorch for cpu on master

---

Dockerfile

Otherwise, the package gets silently removed.

Move gensim after downgrading to python 3.6

---

Dockerfile
Jenkinsfile
build
gpu.Dockerfile
push
test
tests/common.py
tests/test_nvidia.py
tests/test_pytorch.py
tests/test_tensorflow.py

This still keeps two images and won't require any changes to the worker codebase. Moving to a single image will be done later (design doc will be sent out soon).
Since this new GPU image is based off the CPU image, it reuses most of the layers which reduces the disk space used for the python images.
* Installed tensorflow from pre-built wheels (see #302).  Shaves 1h30 minutes from the build time (45 minutes to build the cpu version and 45 minutes the gpu version). This is the same approach colab took and once they migrate to cuda 9, we will be able to share these wheels. This allow for faster iteration time and easier image fixing/debugging in the future.
* Added a `gpu.Dockerfile` to build an image with cuda/nvidia support and pytorch & tensorflow with GPU support
* Updated the `build`, …

Build CPU & GPU images from the same branch

---

tests/test_lightgbm.py

The latest version of the lightgbm package was depending on an old version of libc.
The following error message is shown to users who try to import it:
```
OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by /opt/conda/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so)
```
I pinned the package to the previous version here: 
https://github.com/Kaggle/docker-python/commit/8ff8232d975e2b0a4b8cc11c4083624d2cb9b774

Add test for the lightgbm package

---

build

> --pull | Always attempt to pull a newer version of the image
https://docs.docker.com/engine/reference/commandline/build/#options

Always pull the latest parent images at build

---

gpu.Dockerfile
tests/test_keras.py

Tensorflow requires cuDNN >= 7.2:
https://www.tensorflow.org/install/gpu#software_requirements
This caused a runtime issue for our users trying to do DeepLearning using tensorflow and GPUs:
https://www.kaggle.com/product-feedback/66339#390769
I pushed an image with this fix yesterday and this change just reflects that change. 
I added an extra test that uses DeepLearning to exercise cuDNN.

Install cuDNN 7.2

---

Dockerfile
tests/test_hep_ml.py
tests/test_lasagne.py

Part 1 of many PRs to try to standardize the way we install our packages.
I expanded the tests to prevent regression.
`lasagne` is not in pipy so I installed it using pip git install.
`xgboost` and `hep_ml` had the same version in pipy than the one we were using.

Install hep_ml, xgboost and lasagne using pip

---

Dockerfile

The package was broken for quite a while and no user noticed/complained. 
The last update on github for this package was 3 years ago and the package is still marked as an alpha and in active development, which is clearly not the case.

Removing unmaintained and unused opendeep package

---

Dockerfile

The packages we installed before we downgrade to 3.7 will be reinstalled for 3.6 but some of their settings or versions may not have been kept.
For instance, for the spacy package, we download the en_core_web_lg model. However, this model gets installed under /opt/conda/lib/python3.7/site-packages/ but later, spacy is reinstalled for 3.6. The result is that this model is not usuable but still present on the image.
To avoid these sorts of trouble, we should not install packages before we reinstall the python version we want.

only install packages after downgrading to python 3.6

---

Dockerfile

Fixes #340 and #315.
We will wait before we update fastai to 1.0 until pytorch 1.0 is officially released.

Pin fastai to 0.7.0

---

README.md

Related to #316
We will continue updating the DockerHub registry with the images we deploy to Kaggle Kernels.

Update README to mention that GCR is the source of truth for our docker images

---

Dockerfile

plotnine 0.5 is depending on matplotlib >= 3.0 which is not compatible with basemap.

Prevent upgrade of matplotlib

---

Dockerfile

* geos is now installed using apt-get.
* this version of anaconda is based on debian 9 (as opposed to 8 currently). I updated several packages because the older version where not available for the newer debian
* removed libjasper (not maintained and not available anymore for debian 9), magick uses openjpeg library instead

Upgrade anaconda base to 5.2.0

---

Dockerfile

fasttext depends on pybind11. Using pip to install this package makes sure this dependency is satisfied.
Prior to this change, the build was failing with the following error:
```
Oct 25 13:07:46   ModuleNotFoundError: No module named 'pybind11'
```
-- https://ci.kaggle.net/job/docker-python/job/master/251/consoleText

Install fasttext using pip git feature

---

patches/sitecustomize.py

A little while back, we had issue with hiting the size limit for loading object in static TLS (thread local storage). A workaround was to preload those libraries. Newer versions of these libraries and their dependencies reduce the use of static TLS.
Removing the preloading of these libraries will make using `pip install` and the like in kernels easier.
I ran our test suite and the kernel reported by a user originally that was causing TLS issue and they all run: https://www.kaggle.com/kmader/library-overload
BUG=118388247

Don't preload tensorflow and torch

---

Dockerfile
tests/test_dipy.py
tests/test_xvfbwrapper.py

Closes #359 by providing a workaround consisting of framebuffer X server that can be used to render visualizations offscreen on headless nodes. Example:
```
from dipy.viz import window
from xvfbwrapper import Xvfb
vdisplay = Xvfb()
vdisplay.start()
ren = window.Renderer()
window.record(ren, n_frames=1, out_path='test.png', size=(600, 600))
vdisplay.stop()
```
Ideally (from user convienience point of view) Xvfb should be started automatically via bash wrapper script set as an ENTRYPOINT, but that could lead to some unforseen side effects so I would suggest leaving this for another PR.

Adding xvfb and xvfbwrapper

---

patches/sitecustomize.py

If fastai is used prior to tensorflow, an older version of libcudnn is loaded and tensorflow fails with the following error message:
```
tensorflow/stream_executor/cuda/cuda_dnn.cc:343] Loaded runtime CuDNN library: 7.1.2 but source was compiled with: 7.2.1.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
```
Preloading for now (like before) until we find how to fix the issue with fastai
This issue was caught by our test suite and wasn't released to Kaggle Kernels users.

Preload tensorflow

---

Dockerfile

This breaks the twosigma competition because the code for both lives in a python package called `kaggle`.
The code for the twosigma competition under `kaggle.competitions` should probably be move.
Additionally, the kaggle api client package requires an API secret key. We don't offer a way to manage secrets for now and we don't want to encourage people adding their secret in the code (easy to leak if ever made public).

Remove the kaggle api package

---

gpu.Dockerfile
tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile
tensorflow-whl/README.md
tensorflow-whl/build
tensorflow-whl/push

Similar to the approach taken by Colab. This shaves off 1h30 minutes from the main build process and allow faster iterating/debugging/fixing of the python Docker image.

Create a process to prebuild tensorflow wheels

---

Dockerfile
clean-layer.sh
gpu.Dockerfile

Each RUN commands in our Dockerfiles creates a new layer that is stored separately to disk.
The size of an image is the SUM of all these layers.
When using pip, apt-get or when installing packages from sources, many of the files used to produce the final binary are useless after and can be remove. 
Given that each layer is stored separately, we should clean up the filesystem of these files at the end of each RUN commands.
BUG=120229018

 Cleanup useless files for each image layers

---

tensorflow-whl/Dockerfile

This pull request is intended to solve [this issue](https://github.com/Kaggle/docker-python/issues/404). A much nicer solution would have involved changing 
https://github.com/Kaggle/docker-python/blob/153c087f646ae16fd2a513a1f45f304652c56cba/tensorflow-whl/Dockerfile#L60
to the following:
```apt-get update && apt-get install -y bazel=0.15.0 && \"```
Unfortunately, until [this][1] issue is resolved, @drigz [suggestion][2] works for now.
[1]: https://github.com/bazelbuild/continuous-integration/issues/128
[2]: https://github.com/bazelbuild/continuous-integration/issues/128#issuecomment-356224187

Explicitly install bazel version 0.15.0

---

test

This is useful when running the tests against an image in gcr.io instead of a locally built image.

Allow running test suites against arbitrary images

---

gpu.Dockerfile
tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile
tensorflow-whl/Jenkinsfile

Next: Update our CPU and GPU Dockerfiles to use the latest tensorflow version.

Build tensorflow wheels 1.12 with cuda 9.2

---

Dockerfile
gpu.Dockerfile

Once deployed to Kaggle Kernels, this change will resolve these issues:
- #388 
- #398

Use tensorflow 1.12 wheels and cuda 9.2

---

gpu.Dockerfile

From @guitarmind,
I'm participating [Quora Insincere Questions Classification](https://www.kaggle.com/c/quora-insincere-questions-classification) competition right now and it is limited to provide only 2-CPUs, 14GB RAM and a K80 GPU in 2 hours kernel run time. Therefore it is crucial for kagglers to be able to utilize CUDA library and its interfaces to build performant custom networks in Tensorflow or PyTorch under such limited resources.
[cupy](https://github.com/cupy/cupy) and [pynvrtc](pynvrtc) are commonly required packages.
Some examples about their usage:
- `Quasi-Recurrent Neural Networks` ([QRNN](https://github.com/salesforce/pytorch-qrnn))
- `Independently Recurrent Neural Networks` ([IndRNN](https://github.com/Sunnydreamrain/IndRNN_pytorch))
I've built it successfully by …

Add cupy and pynvrtc to GPU Dockerfile for custom networks in CUDA

---

Dockerfile
README.md
tests/test_pytext.py

PyText has recently been open sourced by Facebook to enable faster NLP experimentation: 
https://code.fb.com/ai-research/pytext-open-source-nlp-framework/
It's likely to be super useful for all NLP competitions, such as the current Quora one:
https://www.kaggle.com/c/quora-insincere-questions-classification
Specifically, the Quora competition is a kernel submissions only *and* we cannot use internet connection enabled kernels, which is what brought me here. 
I've added the `pip install pytext-nlp` to the `Dockerfile`.
Also, I've fixed a broken URL in the `README` -- the guide was giving a 404.

Adding pytext-nlp to the kernel image

---

Dockerfile

cartopy requires numpy > 1.16.0
scikit-image#latest requires numpy <= 1.15.4 (pinned to the PR fixing the numpy 1.16.0 support)

Upgrade numpy and scikit-image

---

Dockerfile

`scikit-image` 0.14.2` was released which fixes a compatibility issue with `numpy` 1.16:
https://pypi.org/project/scikit-image/#history

Remove pin for scikit-image

---

Dockerfile

cartopy fails to install with pip 19.0.1.

Pin pip to 18.1

---

Dockerfile

The pin is no longer necessary. The latest version fixed the issue.

Remove pin for keras_(applications|preprocessing)

---

Dockerfile
patches/kaggle_secrets.py
tests/test_user_secrets.py

We're moving the JWT to the body from the header, as the current Mediator framework in the Web Tier doesn't pass headers to the Service/Controllers.

Move JWE to request body instead of header.

---

Dockerfile
gpu.Dockerfile
tests/test_mxnet.py
tests/text_mxnet.py

This pull request adds GPU version of MXNet to GPU kernel + GluonNLP and GluonCV toolkits to both kernels.
I use pure (not MKL version) of MXNet in case MKL is not supported on the host.
I use CUDA 9.2 version, as I see other packages of GPU kernel relies on 9.2 version of CUDA. Feel free to change to MKL versions if it is guaranteed to present on the host: `mxnet-mkl` and `mxnet-cu92mkl` packages for CPU and GPU respectively.
Relates to https://github.com/Kaggle/docker-python/issues/452
@rosbo, thanks for fixing the master!

Add MXNet GPU + GluonNLP and GluonCV toolkits

---

Dockerfile
Jenkinsfile
build
gpu.Dockerfile

The Jenkins pipeline allows building branches with the `-ci` suffix. 
However, running multiple builds in parallel had a race. 
Part of the pipeline is executed on a CPU-only agent and another part is executed on a GPU agent. Docker Images are transferred between these agents using the Registry but all the parallel builds were writing to the same image tag (race).
This ensures that a different Docker image tag is used when building different branches.

Allow parallel branch builds

---

Dockerfile
tests/test_optuna.py

This PR adds [optuna](https://optuna.org/), which is an automatic hyperparameter optimization framework, particularly designed for Machine Learning. 
Although a similar request can be seen in PR #411, it has not shown any progress for several months.
So, I would like to create this request to add optuna as a new PR.
I confirmed that both `./build` and `./test` worked fine in my local machine.

Add optuna and tests.

---

Dockerfile
gpu.Dockerfile
patches/tensorboard/notebook.py
tests/data/jupyter_tensorboard.ipynb
tests/test_jupytertensorboard.py

To use:
```
%load_ext tensorboard.notebook
%tensorboard --logdir /logs
```

Add TensorBoard to Kaggle Kernels

---

patches/kaggle_gcp.py

https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/credentials.py#L45

Properly store access token so it can be used by credentials object.

---

Dockerfile
gpu.Dockerfile
tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile

Note: The tensorflow wheel is built in a separate pipeline to reduce build time in the main pipeline. See go/kkb-python-image-build for more info on the build process.
The build succeeded: https://ci.kaggle.net/job/kernels/job/docker-python/job/upgrade-tf-cuda-ci/7/
BUG=125933441

Upgrade to cuda 10.0 and Tensorflow 1.13

---

patches/kaggle_gcp.py
tests/test_bigquery.py

Title should be fairly self explanatory but our primary goal is to be able to pass in a default job config to the public bigquery client. This is my first time releasing code for docker-python but I ran build and test and everything seemed good. Please LMK if this doesn't meet standards in any way or if there's anything else I need to adjust here.

Added support for args and kwargs when using the public bigquery proxy

---

Dockerfile
tests/test_pytorch_ignite.py

Adds `ignite` recently released library to help with training neural networks in PyTorch
More info [here](https://pytorch.org/ignite/)
- docker image built and tested as described in README

Add pytorch-ignite with test

---

Dockerfile

The downloader prompts for retry on failure
```
May 27 21:05:51 Error installing package. Retry? [n/y/e]
May 27 21:05:51 [0m[91mTraceback (most recent call last):
May 27 21:05:51   File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
May 27 21:05:51     "__main__", mod_spec)
May 27 21:05:51   File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
May 27 21:05:51     exec(code, run_globals)
May 27 21:05:51   File "/opt/conda/lib/python3.6/site-packages/nltk/downloader.py", line 2583, in <module>
May 27 21:05:51     halt_on_error=options.halt_on_error,
May 27 21:05:51   File "/opt/conda/lib/python3.6/site-packages/nltk/downloader.py", line 798, in download
May 27 21:05:51     choice = input().strip()
May 27 21:05:51 EOFError: EOF when reading a line
```
This …

Retry nltk.downloader on error

---

patches/kaggle_gcp.py
patches/log.py
patches/sitecustomize.py

This is mostly based on the logging done in the worker, minus the asyncio stuff (since this is a much simpler situation). 
We can turn off logging to a file by setting the env var KAGGLE_LOG_TO_FILE = False, and it will log to stdout/stderr, which can help for debugging unit tests. But it defaults to /tmp/kaggle.log.
I believe this is safe, but please consider the security/privacy implications of this as well when reviewing. My understanding is that this will stay only in the user's kernel, during runtime, and so can be used for debugging if a user reaches out to us.

Adds file logging to Kaggle libraries to ease debugging.

---

Dockerfile

Fixes failure introduced by #554.
The image fails to load and run tests because of the missing `log` module in sitecustomize.py
cc/ @vimota @erdalsivri

Include the log.py file into the Docker image

---

Dockerfile

The build succeeds: https://ci.kaggle.net/job/kernels/job/docker-python/job/fix-datashader/4/
However, the tests are failing for a different reason (pthread_cancel and libgcc), I will fix it in a different PR.
BUG=134599839

Prevent llvmlite downgrade by pinning numba package

---

Dockerfile
gpu.Dockerfile

The latest version of pytorch doesn't have incompatibilities with our other packages.

Remove version pin for pytorch

---

Dockerfile

Removing unnecessary version pin (causes a downgrade and the latest version is fine).
This package is already installed near the top of the Dockerfile:
https://github.com/Kaggle/docker-python/blob/master/Dockerfile#L24

Remove python-dateutil pin

---

Dockerfile

The latest version of tornado has a bug that breaks Jupyter notebook: https://github.com/jupyter/notebook/issues/4439

Downgrade tornado to the last known good version to fix notebook issue

---

gpu.Dockerfile
tests/test_keras.py
tests/test_tensorflow.py

- Use cuDNN 7.5.0, this is the version the tensorflow wheels are built with: https://github.com/Kaggle/docker-python/blob/master/tensorflow-whl/Dockerfile#L41
- Added more tests to prevent regression.
The new `test_cudnn_lstm` fails with the last bad release:
```
Traceback (most recent call last):
File "/input/tests/test_keras.py", line 59, in test_conv2d
model.fit(x_train, y_train, batch_size=32, epochs=1)
File "/opt/conda/lib/python3.6/site-packages/keras/engine/training.py", line 1039, in fit
validation_steps=validation_steps)
File "/opt/conda/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
outs = f(ins_batch)
File "/opt/conda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
return self._call(inputs)
File …
```

Use cuDNN 7.5.0 

---

Dockerfile
build

Fixes #532 
Added the git commit hash and the build date to:
- Docker image LABELs
- Files under /etc (to easily run cat /etc/git_commit inside the kernel editor)
This allow to correlate easily an image with a specific git commit hash and build date.

Add LABELs and files in /etc/ to identify build

---

patches/sitecustomize.py
tests/test_gcs.py

Similarly to BigQuery integration, we'd like to use `KaggleKernelCredentials` for GCS integration if no `Credentials` object is provided when constructing GCS client.

Set KaggleKernelCredentials as default for GCS

---

Dockerfile
tests/test_category_encoders.py

We want to use CountEncoder from category_encoders but it isn't
available from the version on PyPI. However, it has been merged into
the master branch on the GitHub repo. So, install from GitHub!
I've also included a test to make sure we can use CountEncoder.

Install category_encoders from GitHub

---

patches/kaggle_gcp.py
patches/sitecustomize.py
tests/test_gcs.py

Instead of monkeypatching by changing `storage.Client` to a lambda, we just mokeypatch the `storage.Client`s constructor.

Change monkeypatching for GCS

---

Dockerfile

The `annoy` build was broken, potentially by https://github.com/spotify/annoy/issues/402.  I reverted to the previous release.
The `geopandas` module failed to load due to missing `libspatialindex`, which is required by `rtree`, which is itself apparently an optional req for `geopandas`, but somehow became a required req, so I just added it.

Fix 'annoy' build and 'geopandas' test

---

Dockerfile

A new version of Keras (2.2.5) was released on August 22nd 2019 and the build has been failing since then.
The previous green build was using Keras (2.2.4) released in October 2018.
The build error was:
Aug 29 17:01:30 AttributeError: module 'keras.backend' has no attribute '_BACKEND'
The latest version of Keras has tensorflow as its default backend. No need to configure.
I remove the default backend configuration logic which was causing the issue.
The build is now passing but an unrelated test failure caused by pytorch will also need to be addressed (in a different PR):
Aug 29 17:01:30 AttributeError: module 'keras.backend' has no attribute '_BACKEND'
BUG=140243312

Fix build failure while configuring Keras

---

Dockerfile

The `pytorch/audio` build is currently broken: https://travis-ci.org/pytorch/audio/jobs/578519924
The issue has been [reported](https://github.com/pytorch/audio/issues/262). This change pins our build to the last good commit.
BUG=140432752

Pin pytorch/audio to the last good commit to work around broken build

---

Dockerfile

numpy 1.17 (latest) is causing annoying deprecation warnings to be printed in users notebook when they use TensorFlow. TensorFlow has a fixed which will be included in the 1.14.1 version (not yet released).
For now, let's pin numpy. We can remove the pin once TensorFlow release 1.14.1.
BUG=140423854

Keep numpy 1.16.4 to prevent deprecation warning

---

Dockerfile

The allennlp package dependencies are installed manually because of a compatibility issue with unnecessary dependencies (e.g. awscli).
A new version of `allennlp` was released on August 21st 2019 which added a new dependency. This PR simply adds it to the our Dockerfile:
https://github.com/allenai/allennlp/blob/27ebcf6ba3e02afe341a5e62cb1a7d5c6906c0c9/requirements.txt#L64
BUG=140440350

Add missing allennlp dependency

---

Dockerfile

incompatible with TensorFlow >= 1.13 (we are using 1.14 and we are moving to 2.0)

Remove ethnicolr

---

patches/kaggle_gcp.py
patches/sitecustomize.py
tests/test_automl.py

I'm not sure how best to test the credential patching. The AutoML clients don't have a credentials attribute. They pass the credentials 5 layers deep into the gRPC library and it's not clear that the credentials end up as an attribute on any of the objects. I think they just end up captured in a closure.
I added a _kaggle_credentials attribute so that the unit tests can at least verify that the credentials were set in the monkeypatch_XXX functions, but it seems questionable to leave that there in the final image. 
The automl_v1beta1.GcsClient can't be patched because no project is passed in anywhere and setting the credentials without a project causes the underlying storage.Client to try to find a default project in the environment which fails. Passing a storage.Client into the GcsClient …

Add monkey patching of the automl clients

---

Dockerfile
tests/test_catalyst.py

Hi, just want to add [Catalyst](https://github.com/catalyst-team/catalyst) - high-level PyTorch framework for reproducible and fast R&D.

Update Dockerfile to add Catalyst

---

Dockerfile

To easily find an image with the TensorFlow version matching the TPU server version.

Add Docker label with TensorFlow version

---

Dockerfile

The anaconda base image has been upgraded in July. The pin on numba is not necessary anymore. The version included in the base image (0.45) and its llvmlite package are now working. Removing the pin prevent's having to reinstall llvmlite.

Remove numba pin version as the base image was upgraded

---

Dockerfile
tests/test_automl.py

Fixes the build issue with pytorch/audio. This was an issue previously, I submitted issue https://github.com/pytorch/audio/issues/262 and the change was rolled back. The change was rolled forward again on 2019-10-23. We should try to move to a conda install of torchaudio-cpu (along with the current conda install of pytorch-cpu and torchvision-cpu) for CPU-only kernels, but it currently fails with package conflicts.
The other change is to revert google-cloud-automl to the previous version (0.6.0) until they release a version with the fix for https://github.com/googleapis/google-cloud-python/issues/9490 which is currently in flight. This issue impacts the AutoML integration which we are announcing on Nov. 4.

Pin pytorch/audio and google-cloud-automl to previous working versions

---

tests/test_fbprophet.py

Failure:
```
Traceback (most recent call last):
File "/input/tests/test_fbprophet.py", line 16, in test_fit
forecaster.fit(train)
File "/opt/conda/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1116, in fit
stan_fit = model.sampling(**args)
File "/opt/conda/lib/python3.6/site-packages/pystan/model.py", line 756, in sampling
raise ValueError("Warmup samples must be greater than 0 when adaptation is enabled (`adapt_engaged=True`)")
ValueError: Warmup samples must be greater than 0 when adaptation is enabled (`adapt_engaged=True`)
```
BUG=143471688

Fix fbprophet tests following new pystan version release

---

Dockerfile

If an ARG is changed, all the layers following it are invalidated from the cache and needs to be rebuild.
The git commit or the build date changes frequently which prevents a fast build/test workflow relying on the docker cache.

Moving ARG and LABELS at the bottom of the file.

---

Dockerfile
tests/test_catalyst.py

The version of google-cloud-automl was pinned to 0.6.0 to resolve the issue in [b/143373325](http://b/143373325). The fix for the original issue was released in google-cloud-automl 0.7.1. This change removes the pinning and goes back to the latest version of the library.
test_catalyst change: Epoch numbering changed in [Catalyst 19.11](https://github.com/catalyst-team/catalyst/releases/tag/v19.11) (PR: https://github.com/catalyst-team/catalyst/pull/411). The master build is [currently broken](https://ci.kaggle.net/job/kernels/job/docker-python/job/master/626/console) by this issue.

Update google-cloud-automl to latest version and fix broken test for Catalyst

---

Dockerfile
gpu.Dockerfile
tests/test_jupytertensorboard.py

TensorBoard adds anywhere from 4s to 10s+ latency when starting any Python Notebook.
Re-enable TensorBoard once a solution to enable TensorBoard only when a user uses it is implemented.
BUG=139212522

Disable TensorBoard

---

Dockerfile

pytext-nlp >= 0.2 requires specific package versions:
```
$ cat pytext_nlp-0.2.2.dist-info/METADATA
Requires-Dist: attrs (==19.1.0)
Requires-Dist: boto3 (==1.9.207)
Requires-Dist: botocore (==1.12.207)
Requires-Dist: certifi (==2019.6.16)
Requires-Dist: cffi (==1.12.3)
Requires-Dist: chardet (==3.0.4)
Requires-Dist: Click (==7.0)
Requires-Dist: docutils (==0.14)
Requires-Dist: fairseq (==0.8.0)
Requires-Dist: fastBPE (==0.1.0)
Requires-Dist: future (==0.17.1)
Requires-Dist: hypothesis (==3.88.3)
Requires-Dist: idna (==2.8)
Requires-Dist: jmespath (==0.9.4)
Requires-Dist: joblib (==0.13.2)
Requires-Dist: numpy (==1.17.0)
Requires-Dist: onnx (==1.5.0)
Requires-Dist: pandas (==0.25.0)
Requires-Dist: portalocker (==1.5.1)
Requires-Dist: protobuf (==3.9.1)
Requires-Dist: pycparser (==2.19) …
```

Pin pytext-nlp to avoid numpy and torch downgrade.

---

Dockerfile

BUG=143372552
Previously needed when we installed torchaudio from #657 but not needed now that we are installing it from conda.

Remove unused flags and dependencies for torchaudio

---

Dockerfile

On December 5th 2019, a new version cesium was released which adds a dependency on scikit-learn==0.20.0 which is causing a failure with the wordbatch package. See related BUG.
BUG=145856222

Pin cesium to avoid scikit-learn downgrade

---

Dockerfile
tests/test_earthengine.py

follow-up to previous PR that lacked a test case: https://github.com/Kaggle/docker-python/pull/652

add earth engine api

---

Dockerfile
tests/test_transformers.py

Add https://github.com/huggingface/transformers repository formerly `pytorch-transformers` and `pytorch-pretrained-bert`.
Not sure should `pytorch-transformers==1.1.0` be then deleted or not.
Relevant kaggle discussion: https://www.kaggle.com/c/google-quest-challenge/discussion/118864

add huggingface/transformers

---

tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile

TensorFlow 2.1.0 GA was released on 1/9/2020.

Build TensorFlow 2.1.0 whl

---

Dockerfile
patches/kaggle_datasets.py
patches/kaggle_secrets.py
patches/kaggle_web_client.py
tests/test_datasets.py

This will support TPUs and AutoML for now. The new `kaggle_web_client.py` file is a copy of the request code currently in `kaggle_secrets.py`. The intent is to follow up and move the shared constants (`_KAGGLE_*`) from kaggle_secrets and have both files use the common code in kaggle_web_client. Given the tight deadline, I didn't want to introduce unnecesary changes in this PR which could break integrations that are already launched.

Add a Kaggle dataset client to support getting GCS paths

---

Dockerfile

pandas 1.0.0 was release on January 30th 2020. 
Unfortunately, the `qgrid` and `tsfresh` packages are incompatible with the latest version of pandas:
- tsfresh: https://github.com/blue-yonder/tsfresh/issues/623 (currently fixed in master but waiting for new release).
- qgrid: https://github.com/quantopian/qgrid/issues/287 (no fixes in yet).
Pinning the pandas version to the previous release until these packages support pandas 1.0.0
BUG=148783763

Pin pandas to 0.25.3

---

patches/kaggle_web_client.py

A short-term workaround for [b/148937154](http://b/148937154) until [b/148790385](https://b.corp.google.com/issues/148790385) can be implemented.
Increases the timeout on the web request backing the get_gcs_path function from 90 seconds to 600 seconds. This should cut down on the timeouts that we've seen in testing.

Increase the timeout for potentially slow web request

---

Dockerfile

We added the pining because pip `20.0.1` introduced an issue with wheels tag matching. See b/148097039.
pip `20.0.2` has since been released and fixes the issue: 
https://github.com/pypa/pip/issues/7626

Install latest version of pip.

---

Dockerfile

Latest version has fixed the issue requiring the pin in the first place.
BUG=144569992

Unpin pyproj

---

Dockerfile

The latest version requires entrypoint >= 3 which is already satisfied in the base image which doesn't trigger a distutil reinstall.

Unpin flake8

---

Dockerfile

cesium 0.9.10 required `scikit-learn==0.20.0` which was causing an unwanted downgrade of this library.
cesium has since released a new version (0.9.12) which requires `scikit-learn>=0.22.1` which doesn't cause a downgrade. This requirement is already satisfied.

Unpin cesium

---

Dockerfile

The dependency on `PyYAML` causing issue has been removed: https://github.com/aws/aws-cli/issues/4042 
See #548 and https://github.com/aws/aws-cli/issues/4042

Remove manual install of allennlp dependencies

---

tests/common.py
tests/test_keras.py

Tests relying heavily on the GPU like the keras test and the upcoming LightGBM GPU test can't be run concurrently.

Use semaphore to control access to GPU in tests

---

tests/test_automl.py

Version 0.10.0 was released an hour ago which caused the tests to start failing.
The current check was converting `0.10` to a float (becomes `0.1`) which is less than `0.5`.

Fix automl version test check

---

patches/kaggle_gcp.py
tests/test_automl.py

When the integration initially launched, there was only the v1beta1 version of the clients. As of Nov. 2019, there is a v1 version but we never updated the code to patch the v1 clients. Addresses [b/149264883](http://b/149264883)
This change includes:
- patching for v1 clients
- remove version test which is no longer needed
- remove exclusion of setting client_info for the TablesClient
Note: `TablesClient` is still in beta, so only `AutoMlClient` and `PredictionServiceClient` have v1 versions.

Patch the AutoML v1 clients to get Kaggle managed credentials

---

Dockerfile

#708 removed the manual install of allennlp dependencies which caused a downgrade of spacy. The constraint set is too strict. It is still working with spacy 2.2.3

Prevent spacy downgrade by allennlp

---

Dockerfile

`distributed` 2.11.0 fails while trying to reach out to 8.8.8.8 since the network is disabled in our hermetic tests .
Full context: b/150498764

Pin distributed

---

tests/test_geoviews.py

The `height` option is not valid for the `matplotlib` backend.
It has been a warning for a little while but is now an error and makes our test fail:
```
WARNING:param.main: Option 'height' for Feature type not valid for selected backend ('matplotlib'). Option only applies to following backends: ['bokeh']
```
BUG=151656948

Remove unsupported parameters in geoviews test

---

gpu.Dockerfile

Fixes `ValueError: jaxlib is version 0.1.38, but this version of jax requires version 0.1.41.` error during docker-python build

Bump jaxlib version to fix build error

---

Dockerfile

Seems that conda fails due to deep dependency conflicts, started without changing much on our side. Looks like they recently added `unsatisfiable_hints_check_depth` (https://github.com/conda/conda/pull/9560/files) which can be configured to do more shallow checks. This PR does exactly that.

Add config to skip deep conda dep checks

---

Dockerfile

Usage: 0 kernels per day
Rational:
Unmaintained, hasn't been updated since 2016, no usage. 10 stars on GitHub.

Remove dora package.

---

Dockerfile

Usage: 0 kernels per day.
Rational:
Unmaintained (last commit 2017), 0 GitHub stars, originally added to our Docker image by the package author.

Remove hallucinate package

---

Dockerfile

Just a clean up while I'm digging through some of these installs. Saw that the git blame for these lines were very old (4 years+), probably safe to pip install now.

Use pip instead of manual install of pybrain, Theano, and nolearn

---

Dockerfile

This package is unmaintained and hasn't been updated since 2017. Keras is now the preferred high-level library for writing TensorFlow code.
Additionally, this package was broken because it requires TensorFlow 1.x and we are using 2.x
BUG=152539178

Remove tflearn package

---

Dockerfile

Usage: 0 kernels per day.
Rational:
Unmaintained. Deprecated in favor of vega. Low GitHub stars, will consider add vega if > 1000 stars and if someone ask for it.
Some people are using Altair which requires vega to display the chart. It requires `vega` and not `vega3`. People are using the `pip install` workaround which is the preferred way to do for not very popular packages that are not required in KO competitions. See:
https://www.kaggle.com/general/63534

Remove vega3 package

---

Dockerfile

Unmaintained (last commit in 2018). `edward` is a probabilistic programming language built on top of TensorFlow 1.x. This doesn't work with TensorFlow 2.x which means this package is effectively broken.
BUG=152539178

Remove edward package

---

Dockerfile

Unmaintained (last updated in 2017). This is a fork of the Stanford `glmnet` package. The `glmnet` packages is still maintained but has a low # of stars on GitHub. We can consider adding the `glmnet` package if it attracts > 1000 stars and if someone asks for it.
BUG=152539178

Remove glmnet-py package

---

Dockerfile

Unmaintained (last updated in 2017) and only works with TensorFlow 1.13. For that reason, this package is effectively broken in our environment.
BUG=152539178

Remove keras-rcnn package.

---

Dockerfile

Usage: 0 kernels / day
Rational:
Unmaintained (last updated in 2017), only 12 GitHub stars, no usage.
Our users can install it with `pip install` if they ever need to.
BUG=152539178

Remove pykoko package

---

Dockerfile

Only works with TensorFlow 1.x. For that reason, this package is effectively broken in our environment which has TensorFlow 2.x
BUG=152539178

Remove keras-rl

---

Dockerfile

This package is NOT compatible with Python 3.7. We are in the process of upgrading to Python 3.7: b/142337634
This package hasn't been updated for 2 years and the author said it is abandoned:
> Note From Author : I am currently working on other projects as of now, so have paused updates for this library for the immediate future. If you'd like to help move the library forward by contributing, then do get in touch! I am planning to review at end of year and update the library as required (new version requirements, etc).
-- https://github.com/RJT1990/pyflux
BUG=152539178

Remove pyflux package

---

Dockerfile

Unmaintained (last change in 2018), 7 GitHub stars. No usage.
BUG=152539178

Remove pyeconometrics package

---

Dockerfile

Unmaintained (last change in 2017), 11 GitHub stars. No usage. It is only a single simple function. Our users can use utility scripts for that.
BUG=152539178

Remove rf_perm_feat_import package

---

Dockerfile

Unmaintained (last change in 2015), 2 GitHub stars. No usage.
BUG=152539178

Remove vida package

---

Dockerfile

Package: `paramnb`
Rational:
From the author: 
> Note: ParamNB is no longer maintained; use the much more capable Panel library instead
Last update in 2018, 30 GitHub stars.
Package: `keras-tqdm`
Rational: 
Unmaintained (last updated in 2017) and only works with TensorFlow 1.x. For that reason, this package is effectively broken in our environment.
Package: `trackml`
Rational:
Unmaintained (last updated in 2017) and no usage.
Package: `testpath`
Rational:
No usage, 7 GitHub stars.
Package: `simplegeneric`
Rational:
Not maintained (last update in 2012), no usage.
Package: `safitty`
Rational:
No usage, 29 GitHub stars.
BUG=152539178

Remove unmaintained, broken or unused packages

---

Dockerfile
tests/test_hyperopt.py

Latest release on pip is from January 2020. Installing using pip which uses pre-built whl is faster than building from source. We have no reason anymore to build it for source.
Added a test to prevent regression.

Install hyperopt using pip

---

tests/test_catalyst.py

saffity was removed in #756. Using the json stdlib instead to read the json config file.

Fix catalyst test

---

Dockerfile
patches/imagemagick-policy.xml

- Install `imagemagick` from the conda-forge channel to always pick latest (currently the same version than `conda-forge/label/cf202003`.
- Permissive policy to allow reading all file types which prevent errors like `wand.exceptions.PolicyError: not authorized `/input/tests/data/test.pdf' @ error/constitute.c/ReadImage/412`.
Based on @vimota work in #731

Set imagemagick policy

---

Dockerfile
tests/test_pysal.py

Also added a test.
anaconda and conda-forge have the same version of pysal. Better to use a minimal # of channels because dependencies for a package are also installed from that channel in priority.

Install pysal from conda-forge

---

Dockerfile

The headless package is more lightweight and `h2o` do not need the UI part of the JRE.
BUG=153753638

Install the headless JRE

---

Dockerfile

This is a NoOp since this package is already part of the base image. 
However, we prefer to list it here explicitly. We also already have smoke test for this package.
Accidentally removed in #765, I meant to remove the `--upgrade` flag but I removed the full line instead.

Add back scikit-image

---

gpu.Dockerfile

Fixes error: `ValueError: jaxlib is version 0.1.41, but this version of jax requires version 0.1.43.`

Upgrade jaxlib

---

tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile

Use the new DLVM image to build the new TensorFlow wheel. 
PR #773 makes use of it.

Build new TensorFlow wheel with DLEnv base image

---

gpu.Dockerfile

This approach still allows building the image on a CPU-only machine while being able to run the image with a GPU attached without having to hide the stubs folder with the following `docker run` flag:
```
-v /tmp/empty_dir:/usr/local/cuda/lib64/stubs:ro
```

Remove CUDA stubs at the end of the GPU build

---

Jenkinsfile

CPU Jenkins workers are ephemeral meaning they are recreated between each build.
GPU Jenkins workers are not, the GCP Jenkins plugin doesn't support GPU VMs well.
Every 2-3 weeks, the GPU builds would start failing because the disk has filled up.
We were already deleting dangling images (untagged). However, we were never deleting the old images with a tag (non-dangling). This meant that we kept the images from the last build for a given branch on the worker until the disk filled up causing failures. 
The fix was to manually SSH to the GPU worker and run `docker system prune -a -f` when it happened when a build failure cause by the GPU worker disk filling occured.
With this PR, we won't have build anymore failing for this reason and we won't need to perform that manual SSH step. …

Delete old tagged images from Jenkins GPU worker

---

Dockerfile
Jenkinsfile

The `nvidia/cuda` and `gcr.io/kaggle-images/python-tensorflow-whl` are rarely updated. This means their creation time is very likely > 5 days. Every build, these images are pruned and then redownloaded. This adds several minutes to the build step.
Note: An image inherits the `LABEL`s from its parent image.
Next:
- Add the `kaggle-lang=r` LABEL to the `rcran` image
- Update the Jenkinsfile in `rstats` to delete images with LABEL `kaggle-lang=r`.
BUG=129682568

Restrict which images are being pruned

---

Dockerfile

The container has an installation of libpixman 0.38.0, installed through the conda-forge. This version has a known bug (https://gitlab.freedesktop.org/pixman/pixman/commit/8256c235d9b3854d039242356905eca854a890ba), which can cause issues in any package using libcairo, such as pycairo and openslide, resulting in invalid images. This pull request downgrades the package to 0.34, which is a stable version also included in Ubuntu 18.04.

Downgrade libpixman to 0.34 to circumvent known bug in 0.38

---

Dockerfile

The previous solution caused an inconsistent condo environment. Now I propose to symlink the system library into the condo environment to work around the bug in libpixman 0.38. This prevents inconsistency. Libcairo, which is the only package which directly depends on libpixman also works perfectly fine with pixman 0.34.

Added fix for libpixman 0.38 bug

---

Jenkinsfile
push

There are no guarantees that the worker running the `push` step is the same than the `build` step.
For instance, if you have 2 workers: A & B.
A may build the image.
B may push the image.
In which case, the build fails with:
```
Error response from daemon: No such image: kaggle/python-gpu-build:latest
```

Ensure the image to push is present on the worker

---

Jenkinsfile

We had issues we a test hanging which held up indefinitely one of our GPU worker and had to be killed manually. This is to prevent this from happening.

Add timeout for build/test steps to avoid holding up workers

---

Dockerfile
tests/test_imports.py

Reverts Kaggle/docker-python#788
Breaks tests against GPU build and probably doesn't work with a GPU.
Context: https://kaggle.slack.com/archives/CAHCTF54Z/p1588027289298700?thread_ts=1588026655.298500&cid=CAHCTF54Z

Revert "Install tensorflow-gcs-config from the python-tensorflow-whl"

---

tensorflow-whl/Dockerfile

This matches the GPU build and allows the `tensorflow-gcs-config` wheel/package to work with both CPU and GPU versions of TF.
I've built tensorflow-whl locally with this change and built both the CPU and GPU docker-python images using the local tensorflow-whl image. All tests pass against both the CPU and GPU images.
http://b/152051681

Add GLIBCXX_USE_CXX11_ABI=0 compiler define to TensorFlow CPU build

---

Dockerfile
tests/test_imports.py

Second try at reverted Kaggle/docker-python#788
Update the version of python-tensorflow-whl used in the build and install tensorflow-gcs-config from the wheel.
http://b/152051681

Install tensorflow-gcs-config from the python-tensorflow-whl

---

README.md

URL seems to be changed due to the moving to https://medium.com/.

Fix guide url

---

Dockerfile

Disabling the extensions instead of removing them for two reasons:
- To keep the conda env consistent: https://paste.googleplex.com/6175038124326912
- To allow enabling it at startup if needed in CAIP notebook.

Disable nb_conda & nbpresent jupyter extensions

---

Dockerfile

fbprophet now supports the latest version of the holidays package.
BUG=148383434

Remove holidays pin

---

Dockerfile

We are now using `matplotlib` 3.2 which works with the latest version of these 2 packages.

Remove geoviews & plotnine pins

---

Dockerfile
tests/data/notebook.ipynb
tests/test_papermill.py

papermill provides a bunch of nice features for executing notebooks, including ones not provided by nbconvert.
Some key features we want:
* dump cell output to logs
* stop on cell error, but still include cell output up to the errored cell

pip install papermill

---

tensorflow-whl/tensorflow-gcs-config/tensorflow_gcs_config/gcs_config_op_kernels.cc

Fix C++ build breakage with TF 2.2.0 by integrating the upstream changes from TensorFlow I/O. This is based on the tf-2.2-whl branch.
Upstream change: https://github.com/tensorflow/io/commit/9474c119c9a98338f8f3b2306deef089ed6c3a43#diff-5f97ff36189775824d704c7e560b2e14
File: tensorflow_io/gcs/kernels/gcs_config_op_kernels.cc
http://b/151627748

Update tensorflow_gcs_config source with upstream changes

---

Dockerfile
tests/test_tensorflow_addons.py

Fixes #638 
Note: TFA functionnality relying on Custom Op won't work. See:
https://github.com/tensorflow/addons/issues/987.
BUG=145555176

Add TensorFlow addons (TFA)

---

tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile

TFA must be build from source to support CustomOps. This is necessary
since TensorFlow C++ API is not ABI compatible. See:
- https://github.com/tensorflow/addons/issues/987.

Build TensorFlow addons wheels.

---

tests/test_tensorflow_addons.py

To prevent future regression.
BUG=145555176

Add a test exercising TFA custom op.

---

Dockerfile
tests/test_ggplot.py

Fixes #823 
Upstream does not merge the fix https://github.com/yhat/ggpy/pull/668

Install fixed ggplot

---

Dockerfile

A new base image was released on May 28th. This new image includes numba
0.49.1 and llvmlite 0.32.0. Unfortunately, numba >= 0.49.0 has a
performance regression and packages such as datashader downgrades
it. llvmlite can't be downgraded safely since it is a distutils
package.
Pinning the base image until the numba/llvmlite performance regression
is fixed.
BUG=157908450

Pin base image.

---

Dockerfile
test

* Remove `distributed` package downgrade.
* Fixed tests impacted by change in `distributed` which defaults to `hostname` instead of `localhost` since 2.11.0.
This is necessary for #595 (adding rapidsai) b/c it depends on `distributed` >= 2.12.0
BUG=158137436

Unpin distributed

---

patches/kaggle_secrets.py
tests/test_tensorflow_credentials.py

Set the credential for both the TPU and the local notebook.
https://b.corp.google.com/issues/158133824

Add support for setting the GCS credential

---

Dockerfile
tests/test_allennlp.py

`allennlp` released a new major version (1.0.0) on June 16th. The interface has changed. Test should be updated to use the new interface.
BUG=159175300

Fix allennlp test following major version upgrade

---

tests/test_keras.py

CuDNNLSTM has been removed.
LSTM uses CuDNN on GPU if available.
Fixes test failure:
```
ImportError: cannot import name 'CuDNNLSTM' from 'keras.layers' (/opt/conda/lib/python3.7/site-packages/keras/layers/__init__.py)
```
See: https://github.com/keras-team/keras/blob/b5cb82c689eac0e50522be9d2f55093dadfba24c/keras/layers/cudnn_recurrent.py#L4
BUG=159346043

Use Keras LSTM layer.

---

tests/test_dipy.py

Warning in the log: "Renderer() deprecated, Please use Scene() instead".

Remove use of deprecated Renderer.

---

Dockerfile

This package is already part of our base image and installed through Conda.
This command is a NoOp but confusing given that pip insn't used to install this package.
From the build logs: `Requirement already satisfied: opencv-python`
#825

Remove redundant opencv-python pip command.

---

Dockerfile

The base image includes Pillow 7.1.0 which has a known issue: https://github.com/python-pillow/Pillow/issues/4518
This is causing the skimage test to fail.
BUG=160263325

Use latest version of Pillow

---

patches/kaggle_secrets.py

Import `tensorflow_gcs_config` only when `set_tensorflow_credential` is called to prevent preloading TensorFlow.
BUG=159906185

Delay tensorflow_gcs_config import

---

Dockerfile

conda resolves randomly to 2.1.0 or 1.14.4. Adding an explicit constraint to prevent this flakiness from causing flakiness in our build.
BUG=161473620

Ensures pysal >= 2.1.0 is installed.

---

patches/kaggle_web_client.py

In the future, we will use that custom header instead of a standard `Authorization` header which is used currently.
This is needed in order for us to work with IAP, which also expects an `Authorization` header, see [this doc](https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_a_service_account).

Add X-Kaggle-Authorization header to KaggleWebClient

---

Dockerfile
gpu.Dockerfile

pytorch 1.6 was released on 7/28. However, no new versions of torchaudio
have been released yet which is causing runtime errors:
```
OSError: /opt/conda/lib/python3.7/site-packages/torchaudio/_torchaudio.so: undefined symbol: _ZNK2at6Tensor6deviceEv
```
BUG=162357958

Pin pytorch & torch* libs versions.

---

patches/kaggle_web_client.py
tests/test_datasets.py
tests/test_user_secrets.py

The JWE should now be passed exclusively in `X-Kaggle-Authorization` header.
http://b/148309982

Remove JWE from Authorization header and from the request body.

---

patches/kaggle_web_client.py
tests/test_datasets.py

The token will be injected from the mid-tier in appropriate environment.
http://b/158655418

Pass IAP token via Authorization header when appropriate env var is defined.

---

Dockerfile

Pin packages to prevent torch upgrade

---

Dockerfile

Unpin geopandas

---

Dockerfile
gpu.Dockerfile

Also upgrade to CUDA 10.2.
BUG=165813706

Use TensorFlow 2.3.1 wheel

---

Dockerfile
patches/kaggle_session.py
tests/test_user_session.py

Add new client to retrieve exportable .ipynb of current session.

---

patches/kaggle_secrets.py
tests/test_user_secrets.py

Set gcloud CLI credentials and optionally the project and account.
http://b/170989865

Add set_gcloud_credentials to UserSecretsClient

---

patches/kaggle_secrets.py
tests/test_user_secrets.py

The PR adds a call to `_write_gsutil_credentials_file` which would store the refresh token from gcloud credentials to `~/.boto` file used by `gsutil`. 
https://cloud.google.com/storage/docs/boto-gsutil
http://b/171747843

Store gsutil credentials in .boto file when storing gcloud credentials

---

Dockerfile

fastai 2.1.x uses torch 1.7. Unfortunately, we can't upgrade to torch
1.7 yet. We need to wait until all the libraries depending on torch are
supported 1.7.
http://b/172468280

Pin fastai.

---

Dockerfile
gpu.Dockerfile
tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile

Upgrade TensorFlow addons

---

Dockerfile

We were pinning the fastai version but not the underlying fastcore
package.
The newest version of fastcore wasn't compatible with our pinned version
of fastai.
http://b/173417664

Pin fastcore.

---

Dockerfile

This package is not part of our base image anymore. From the build logs:
```
Nov 27 12:37:40 [91mWARNING: Skipping enum34 as it is not installed.
```

Remove useless pip uninstall enum34 command

---

Dockerfile
tests/test_bayes_opt.py
tests/test_category_encoders.py

And add tests for gaps.
BUG=174361103

Install pkg from pip

---

Dockerfile

Fixes #911.
xgboost was downgraded from 1.x to 0.90 causing pain for XGBoost users (see #911).
This package only works with xgboost <= 0.90: https://github.com/dask/dask-xgboost/blob/master/requirements.txt#L1
The dask-xgboost package has very low usage (~100 over the last 90 days) and only ~100 stars on GitHub.
BUG=175051617

Remove dask xgboost

---

Dockerfile

As per https://github.com/Theano/Theano
> `MILA will stop developing Theano <https://groups.google.com/d/msg/theano-users/7Poq8BZutbY/rNCIfvAEAwAJ>`_.
>
>The PyMC developers are continuing Theano development in a `fork <https://github.com/pymc-devs/theano-pymc>`_.

Replace (deprecated) theano with (maintained) theano-pymc

---

Dockerfile
gpu.Dockerfile

The latest version (1.14) only works with cuDNN 8.x. However, we are
using 7.x. I filed a bug to look into upgrading cuDNN.
For now, pinning to 1.13 to make it work with cuDNN 7.x.
BUG=175636822

Pin nnabla to 1.13

---

gpu.Dockerfile

The latest version do not downgrade numpy anymore: https://github.com/apache/incubator-mxnet/blob/master/python/setup.py#L33

Remove --no-deps from mxnet installation.

---

test

This is causing other GPU library tests to fail because no GPU memory is
available with errors like:
```
lightgbm.basic.LightGBMError: Memory Object Allocation Failure
```
Tested by running the jax_test and having `watch -n 1 nvidia-smi` in a separate window. Before this change, GPU memory usage peaked at ~16GB. After this change it peaks at 10 Mb.
BUG=173553533

Disable JAX memory preallocation

---

Dockerfile

The new 0.24.0 version has been released on Dec 23 but isn't compatible
with several of our packages including hep-ml.
BUG=176817038

Pin scikit-learn to 0.23.2

---

Dockerfile
patches/kaggle_gcp.py
patches/kaggle_secrets.py
patches/sitecustomize.py
tests/test_natural_language.py
tests/test_translation.py
tests/test_user_secrets.py
tests/test_video_intelligence.py
tests/test_vision.py

Add GCP integrations with the latest client major versions of
* Cloud Translation V2 (basic) and V3 (advanced)
* Natural language V2
* Vision V2
* Video intelligence V2
ticket: b/175030896
**Do not merge until corresponding GCP integration controller version released!**

GCP ML services integration.

---

Dockerfile

`umap-learn` 0.5.0 (released on 1/11/2021, today) is causing a llvmlite upgrade.
This library should never be updated because it is a distutils project and cannot be cleanly reinstalled. Packages should be compatible with the version of llvmlite from the base image.

Pin umap-learn

---

Dockerfile
gpu.Dockerfile
tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile
tests/test_tensorflow.py
tests/test_tensorflow_addons.py
tests/test_tensorforce.py

Upgrade from m46 to m61.
Fixes #916

Upgrade base image

---

Dockerfile
tests/test_sympy.py

Required by our Learn vision class.
http://b/177552728

Add sympy package

---

Dockerfile
Jenkinsfile
patches/nbconvert-extensions.tpl
patches/template_conf.json

Use the non-deprecated nbconvert template and add template configuration file.
The config is a breaking change in nbconvert 6.x
https://b.corp.google.com/issues/178057839#comment8

Fix nbconvert template

---

tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile

TensorFlow must be built with 7.0 compute capability.
http://b/178104927

Add support for V100 GPU.

---

Dockerfile
gpu.Dockerfile

Use wheels built in #940 
http://b/178104927

Use new TF wheels with CUDA 7.0 capability support

---

tests/test_lightgbm.py

```
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000252 seconds.
You can set `force_row_wise=true` to remove the overhead.
```

Remove warning from lightGBM test.

---

Dockerfile

Keep jedi package's version in 0.17.2. Lastest version breaks autocomplete on jupyter. https://github.com/ipython/ipython/issues/12740

Keep jedi version 0.17.2

---

Dockerfile

1.1.8 is incompatible with our version of numpy.
http://b/179264579

Pin cvxpy to 1.1.7

---

tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile

- Also upgrade TensorFlow addons to 0.12.1
http://b/179051776

Build new TensorFlow 2.4.1 whl.

---

Dockerfile
tests/test_tensorflow.py

This is used by keras plot_model() function.
Included a test to prevent regression.
Improved the existing tf test with extra assertions.
The issue was raised by a user here: https://www.kaggle.com/c/jane-street-market-prediction/discussion/214494#1184233

Add pydot package

---

test

A test run creates files under the /tmp/python-build directory. The
owner of these files are the user assigned to your docker process.
Running `rm -rf /tmp/python-build` in the test script fails with:
```
rm: cannot remove '/tmp/python-build/working/logs/train_log/events.out.tfevents.1614297217.localhost': Permission denied
...
```
Because your user don't have the permissions to delete these files.
Updating the `test` script to delete these files inside the a docker
container to circumvent this problem.

Avoid having to use sudo for running the tests.

---

Dockerfile
tensorflow-whl/Dockerfile
tests/test_matplotlib.py

- Pin pyproj since 3.x is not compatible with latest version of basemap
yet.
- Improved the basemap test.
http://b/182405233

Upgrade base image to m64.

---

Dockerfile

In #967, I upgraded the base image from `m61` to `m64`.
The new  `m64` base image doesn't include a SSH client anymore.
This was causing issues with a learn course relying on `stable-baselines`. This package isn't included in our base image but is installed at runtime.
http://b/182601974

Install openssh-client

---

tests/test_catalyst.py
tests/test_nnabla.py

Catalyst 21.x was released on 3/13. We were using 20.x. This release
included a breaking change for the CheckpointCallback class which
required updating our test.
Also fixed flaky nnabla test by relaxing the test assertions. 
http://b/182904788

Fix catalyst test.

---

Dockerfile
tests/test_bigquery_storage.py

This library is part of our base image (deeplearning-platform-release)
but not other libraries depend on it.
Removing this library ensures the bigquery library fall backs on using
regular BQ queries to fetch data.
The BigQuery storage APIs are not supported by our data proxy and we
don't monkey patch this client.
This change simply revert to the behavior we had with BQ 1.x libraries.
http://b/183041606

Uninstall google-cloud-bigquery-storage library.

---

Dockerfile

pystan 3.x released on March 25th, 2021 is not compatible with
fbprophet and causing a build failure.
http://b/183944405

Pin pystan

---

Dockerfile
tensorflow-whl/Dockerfile

Currently latest == the one in m66 (i.e. NoOp).
Remove this to prevent unnecessary churn.

Keep the pip version from the base image

---

Dockerfile

`nltk` version 3.6 released earlier today includes a production
dependency on pytest. They are working on a hotfix:
https://github.com/nltk/nltk/pull/2693.
Pinning to 3.5 until the new version is out.
http://b/184748065

Pin nltk to 3.5

---

Dockerfile

A new version of nltk with the hotfix was released an hour ago:
- https://pypi.org/project/nltk/#history
- https://github.com/nltk/nltk/pull/2693#issuecomment-815281396
This reverts commit bda8a17e6a232cab291536e753e03a3b9c965c95.

Revert "Pin nltk to 3.5 (#988)"

---

Dockerfile

3.9.0 is causing a major performance degradation with spacy 2.3.5
Full context: https://b.corp.google.com/issues/184685619#comment9
BUG=http://b/184685619

Pin importlib-metadata

---

Dockerfile

- Use simply the version from our DLVM base image.
- Removed the meta-package `jupyter`. It references packages already
installed.
This ensures we have the jupyter packages in sync with DLVM and ensures
compatibility with the Cloud AI Notebook environment.

Remove pins for jupyter packages.

---

Dockerfile
gpu.Dockerfile
tests/test_jax.py

Fixes #918
Before, we were installing JAX only on the GPU image.
Included tests to prevent regression.
http://b/177334844

Add JAX to the CPU/TPU image.

---

Dockerfile

Adds widget support for matplotlib
http://b/185060120

install ipympl

---

Dockerfile

Latest version of `wand` is compatible with latest version of tesseract

Unpin wand

---

Dockerfile
tests/test_pandarralel.py

Pandarallel allows to execute pandas apply method in parallel, which allows to do data preprocessing faster and easier. This is very helpful in kernel only competitions.
For more information, see:
https://github.com/nalepae/pandarallel

Adding pandarallel library

---

Dockerfile
tests/test_spacy.py

spacy has been upgraded to 3.x (fastai had a 2.x requirement but now
support 3.x which upgraded spacy.)
`en` model name shortcut is no longer available in spacy 3.x

Fix spacy test.

---

tests/test_openslide.py

```
ResourceWarning: unclosed file <_io.BufferedReader name='/input/tests/data/test.tif'>
testMethod()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

Fix warning in openslide test

---

Dockerfile

fastai 2.3.1 upgrades torch and torchvision causing issues.
upgrading torch proved more difficult than I thought (unresolvable
conflicts atm). will handle the upgrade later in b/181966788
http://b/188429515

Pin fastai to 2.2.7

---

Dockerfile

`tensorflow-transform` 1.x released on May 24th is causing an unwanted
upgrade to TensorFlow 2.5.
http://b/188429515

Pin tensorflow-transform

---

Dockerfile

Starting in 1.1.14, `tensorflow-cloud` requires `tensorflow-transform`
which requires `apache-beam[gcp]`. `apache-beam` downgrades the
`google.cloud` libraries to 1.x. However, we are using 2.x
http://b/188429515

Pin tensorflow-cloud to 1.1.13

---

Dockerfile
tests/test_vaex.py

This PR adds the [vaex](https://github.com/vaexio/vaex) library to the docker image. 
Also related to https://github.com/Kaggle/docker-python/issues/928.

Add the vaex library (includes a test)

---

Dockerfile
gpu.Dockerfile

More details at: https://b.corp.google.com/issues/186646069#comment14
http://b/186646069

Use official TensorFlow wheel

---

gpu.Dockerfile

Upgrade cuml/cudf to 21.06

---

Dockerfile

This package is in "bare maintenance" mode and rarely used on Kaggle.
`cvxpy` was only used by the `fancyimpute` package.

Removing fancyimpute

---

gpu.Dockerfile

The `tensorflow` package on `pip` supports both CPU & GPU.
http://b/184083722

No need to reinstall `tensorflow-gpu`

---

Jenkinsfile

In some rare cases, image is built on GPU worker 1 and tests are run on GPU worker 2. If GPU worker 2 has already an image with the `${branch_name}-pretest` tag from a previous build, then, the tests are ran against the wrong image.
Solution: Always pull before running the tests. If the image on the worker is already the latest, this is a NoOp. If it is an image from a previous build, it will pull the latest image from GCR.

Ensures tests are run against the previously built image.

---

Dockerfile
tests/test_tensorflow_probability.py

The latest version of `tensorflow_probability` is not compatible with
our version of TF:
```
ImportError: This version of TensorFlow Probability requires TensorFlow
version >= 2.5; Detected an installation of version 2.4.1. Please
upgrade TensorFlow to proceed
```
Pinning & adding a test to prevent regression.
http://b/194837139

Pin tensorflow_probability to work with TF 2.4.1

---

Dockerfile
gpu.Dockerfile
tests/test_matplotlib.py

conda is too slow to converge and torch can be installed from pip for any cuda versions now.
Removed `basemap` package which has been deprecated in favor of `cartopy`. It had conflicting dependencies and won't be upgraded anymore.

Install torch from pip

---

Dockerfile
tests/test_numpy.py

These are necessary for the TPU pytorch XLA.
They also provide a significant perforance boost.
They used to be automatically included when we were installing torch
from conda but they are not now that we install torch from pip.
I added a test to prevent regression.
http://b/195414519

Install blas & mkl

---

Dockerfile
gpu.Dockerfile

We used to download the nvidia packages using apt over http. However
this is not supported anymore causing a build failure.
After much trial and error, I found that `apt` was not properly using the system certificate because of a broken
LD_LIBRARY_PATH. See the bug below for full context.
Additionally, new versions of `gensim` and `kornia` were released on August 29th and 30th respectively which are incompatible with our version of numpy. I pinned the version of these packages.
http://b/197989446

Fix TLS error when upgrading nvidia packages.

---

Dockerfile
gpu.Dockerfile

- Use new pip install syntax.
- The proper version of jaxlib is installed based on the version of jax.

Upgrade JAX

---

Dockerfile
gpu.Dockerfile

Latest versions causing the following error at runtime:
```
...
File "/opt/conda/lib/python3.7/site-packages/torchmetrics/utilities/imports.py", line 33, in _module_available
return find_spec(module_path) is not None
File "/opt/conda/lib/python3.7/importlib/util.py", line 114, in find_spec
raise ValueError('{}.__spec__ is None'.format(name))
ValueError: transformers.__spec__ is None
```
Also, remove /opt/conda/lib from LD_LIBRARY_PATH only when fetching
packages over https using apt.
Otherwise, this is causing an issue with scipy which expects a different
version of glibc.
http://b/198635596

Pin pytorch-lightning & torchmetrics.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Adding simple templates for:
- reporting bug
- requesting feature
- opening a PR
This will simplify handling all these Maintenence (also automatically add a label)

add GH templates

---

Dockerfile.tmpl

gcloud is already part of the base image.

Remove gcloud installation.

---

Dockerfile.tmpl

We don't build `vowpal_wabbit` from source and LightGBM needs only a subset of libboost-dev librairies.

Remove unnecessary packages

---

Dockerfile.tmpl

The matrixprofile in pip downgrades protobuf because the release whl has
the wrong requirements.txt file.
http://b/205704651

Install matrixprofile from git to solve protobuf downgrade issue.

---

Dockerfile.tmpl

The latest version of `hyperopt` (0.2.6) requires `py4j` but doesn't list it
as a requirement.
This caused our tests to start failing.
`py4j` is a package to access Java objects.
http://b/206631257
Fixes #\<issue_number>

Install py4j

---

Dockerfile.tmpl

Prevent upgrade to numpy 1.21.x.
The latest version of osmx (1.1.2) requires numpy >= 1.21: https://github.com/gboeing/osmnx/blob/6f9236f20a81416bf34186a811a8ebb76afa0dc8/requirements.txt#L4
http://b/206990323

Pin osmx to 1.1.1

---

Dockerfile.tmpl

Removing the CUDA stubs from the `LD_LIBRARY_PATH` should only be done for the GPU build.
`LD_LIBRARY_PATH_NO_STUBS` is not defined for the CPU build causing the LD_LIBRARY_PATH to be set to `""`.
http://b/207036238

Fix LD_LIBRARY_PATH for the CPU image.

---

Jenkinsfile

- Delete only images without the `v*` tag.
- Delete only images older than 9 months (recent unversioned images are
useful for debugging).
http://b/208859194

Delete old unversioned Python images

---

Dockerfile.tmpl

The `hyperopt` package now lists `py4j` as a dependency: https://github.com/hyperopt/hyperopt/blob/dfdb48d1dd9917fad347316a7818a9dcd160f200/setup.py#L51
See: b/206631257

Remove explicit dependency on py4j

---

Dockerfile.tmpl

A new version of `hep-ml` was released on September 10, 2021 which supports scikit-learn 0.24.x

Remove pin on scikit-learn

---

Dockerfile.tmpl

Latest version of `nnabla` is now compatible with latest version of `pynvml`

Remove pynvml pin

---

Dockerfile.tmpl

- 0.2.19 is too old for the latest version of flax.
- Updated command to install the GPU version of JAX since it has changed: https://github.com/google/jax#pip-installation-gpu-cuda
http://b/210130222

Upgrade JAX to latest

---

Dockerfile.tmpl
tests/test_implicit.py

- Installing from pip installs from source. Faster to install binary
from conda
- Fixes build issues since we are building the GPU image with stubs.
- Added a smoke test
http://b/211665716

Install implicit from conda

---

Dockerfile.tmpl

As of yesterday, GitHub no longer supports unauthenticated git:// calls: https://news.ycombinator.com/item?id=29891656
Pinning version of opencv to avoid segfault. See: https://github.com/JaidedAI/EasyOCR/issues/630
http://b/212703016 (opencv segfault)
http://b/214044576 (GitHub issue)

Fix pip install from git and pin opencv

---

tpu/Dockerfile
tpu/README.md
tpu/cloudbuild.yaml
tpu/tensorflow.Dockerfile

TODO:
- Currently fails on Cloud Build but works locally on Cloud Top: https://pantheon.corp.google.com/cloud-build/builds;region=global/904c778d-45c4-4646-9183-f10b18a4910a?project=kkb-infra. May be related to not enough RAM. Will require more investigation.
- TensorFlow related libraries (tensorflow-addons, tensorflow-gcs-config) will need to be recompiled against the new TPU binary.
- Install TPU support for JAX & Pytorch.
http://b/152075195

Build Kaggle TPU image

---

Dockerfile.tmpl

`torchmetrics` 0.7.0 released yesterday (Jan 17th 2022) is causing an issue with pytorch_lightning: https://github.com/PyTorchLightning/pytorch-lightning/issues/11524

Pin torchmetrics.

---

Dockerfile.tmpl

Version 0.8.0 causes test_dipy to break with ImportError: cannot import name 'vtk' from 'fury.window' 
http://b/217761018

pin fury==0.7.1 to fix breakage

---

Dockerfile.tmpl

Latest version of dipy (1.5.0) released last week requires the latest
version of fury (0.8.0).
http://b/224623471

Remove pin of fury

---

Dockerfile.tmpl
tests/test_jupyter_nbconvert.py

The latest version of Jinja changed the import for `Markup`.
The import was fixed in the latest version of `nbconvert`: https://github.com/jupyter/nbconvert/issues/1736
We include the version of `nbconvert` from the DLVM base image which is
released every ~2 weeks. However, the `nbconvert` fix was released only
6 hours ago.
Temporarily install thel latest version of `nbconvert`.
Add a test to prevent regression.
http://b/227194111

Install latest version of nbconvert to fix Jinja issue.

---

Dockerfile.tmpl

This PR integrates accelerated x86 scikit-learn library that brings noticeable performance improvements for scikit-learn as well as set of AutoML frameworks(AutoGluon, autoscikit-learn, PyCaret, etc. ) that are using scikit-learn internally. 
Link to github project - https://github.com/intel/scikit-learn-intelex .  Accelerations achieved through use of oneDAL library  - https://github.com/oneapi-src/oneDAL
There is set of users/notebooks that already use accelerations - https://www.kaggle.com/search?q=scikit-learn-intelex 
Based on demonstrated results across notebooks we see that on Kaggle instances 2x-40x speedups can be achieved. This leads to productivity, results, CO2 reduction improvements.

Adding scikit-learn-intelex package

---

tests/test_sklearnex.py

sklearnex was added in #1135
http://227237481
cc/ @napetrov

Add smoke test for sklearnex

---

Dockerfile.tmpl
tests/test_jupyterlab_lsp.py
tests/test_python_lsp_server.py
tests/test_tsfresh.py

Add dependencies necessary for LSP-based autocomplete.

---

Dockerfile.tmpl
tests/test_hf_datasets.py

- Included a smoke test
http://b/230657835

Add Hugging Face datasets

---

Jenkinsfile

The jenkins SA did not have access to pull the libtpu docker image needed for the TPU VM build.
I started a TPU VM with that SA to grant it access, and added docker login setup to use authenticated docker commands.
http://b/213335159

Fix access to libtpu

---

tpu/Dockerfile

This is necessary to make it available with that build context.
The other ARGs are above because they are used in the FROM statement themselves but not the build context of the last image.
I also updated the URL for installing `torch_xla`. The version of Torch should not include the minor version.

Move TORCH_VERSION ARG below the FROM

---

Jenkinsfile

The ACCESS_TOKEN was being printed in the logs, this should hide it.
http://b/213335159

Hide sensitive output in jenkins

---

Dockerfile.tmpl

This package is causing a downgrade of the `importlib-metadata` package which is causing a cascading number of reinstalls: https://github.com/PyCQA/flake8/blob/9f608813b80caf5a966e44d4bfb5e032159eb3e2/setup.cfg#L45
Flake8 is a style checker for Python but we are not using it AFAIK. We don't have Jupyter plugins for it either.

Remove flake8

---

Dockerfile.tmpl
tests/test_jax.py

Fixes #1178 
Added also a test to prevent regression.
http://b/239603020

Fix GPU support for JAX

---

Dockerfile.tmpl
tests/test_tensorflow_decision_forests.py

Add also smoke test to prevent regression.
http://b/230374952

Add tensorflow_decision_forests package

---

Dockerfile.tmpl
test_pytables.py

Add support for pytables (so pandas can r/w h5 files)

---

Dockerfile.tmpl
Jenkinsfile

The error in the Dec 13th build is `ModuleNotFoundError: No module named 'mock'`.
Also increase timeout for T4 tests.
http://b/262387811

Install mock package

---

Dockerfile.tmpl
Jenkinsfile

Install git-lfs

---

Dockerfile.tmpl
tests/test_pycolmap.py

Adds [pycolmap](https://github.com/colmap/pycolmap) to the image. That is useful for 3D reconstruction and image matching tasks, such as in https://www.kaggle.com/competitions/image-matching-challenge-2022 or https://www.kaggle.com/competitions/landmark-retrieval-challenge/

Add pycolmap

---

Dockerfile.tmpl

this allows pip to resolve eventual version conflicts within particular layers
as it was now, there was no guarantee that the next installed package would break the previous installation (for example, min NumPy version)
I would suggest also doing it in the remaining dockers.
Moreover, reducing duplication may simplify the readability, aka define required packages in extra files and install them within the docker build...
(if agreed, I am happy to make both suggestions :rabbit: )

expand pip install

---

Dockerfile.tmpl
tests/test_tensorflow_text.py

Add tensorflow_text package

---

Jenkinsfile

Tests run fine in 155s when I kick them off manually from a `linux-gpu-*` test worker. Pulling the image + waiting for a GPU worker sometimes takes more time.

Increase timeout for P100 tests

---

Dockerfile.tmpl
tests/test_polars.py

https://www.pola.rs/
polars is an exceptionally performant DataFrame library https://h2oai.github.io/db-benchmark/, which is growing in popularity https://pypistats.org/packages/polars
Any chance it could be added to the Kaggle environment please?

Add polars

---

patches/kaggle_datasets.py

TPU VMs can directly use the Kaggle dataset path in /kaggle/input and therefore this returns that path instead of an on GCS path.
http://b/273529732

KaggleDatasets.get_gcs_path supports TPU VM directly

---

Dockerfile.tmpl
tests/test_imports.py

Code for running inference with the SegmentAnything model: https://github.com/facebookresearch/segment-anything
http://b/277217745

Add segment_anything package.

---

Dockerfile.tmpl
tests/test_jupyter_server.py

This patch upgrades `jupyter_server` 🆙  to version `2.x` 
- Fixes #1247 
- Fixes #1246
Note: GitHub actions [here demonstrate that images build and publish](https://github.com/maciejskorski/docker-python)

upgrade jupyter-server

---

Dockerfile.tmpl

https://stackoverflow.com/questions/68673221/warning-running-pip-as-the-root-user
http://b/288905562

Environment variable to remove the warning when installing with pip in a notebook

---

tests/test_rapidfuzz.py

Existence test for the `rapidfuzz` library, needed for the [Word Error Rate](https://github.com/Kaggle/competitions/pull/260) metric.

Add rapidfuzz existence test

---

Dockerfile.tmpl

Also:
- specify `-y` for `momba install`
- split a long `pip install` which broke with `pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000`
http://b/290035631

Pin Pillow because of a EasyOCR breakage

---

Dockerfile.tmpl
tests/test_transformers.py

Also: 
- use fork of Catalyst to work with the latest Accelerate
- pin keras-cv, the latest version broke test
http://b/254245259

Unpin accelerate to fix transformers pipeline

---

Dockerfile.tmpl
tests/test_kerascv.py

That line is broken in the last version of keras-cv, but wasn't actually used in the test.
I also created a [bug](https://github.com/keras-team/keras-cv/issues/1923) on keras-cv repository.
http://b/290392955

Unpin keras-cv

---

diff

Useful to see if any environment variables have changed between two docker images.

Add printenv to docker image diff script.

---

Dockerfile.tmpl

Added several fixes to resolve the issue
1. Move `cupy` as the first install so that the `cuda` path is resolved correctly
2. Removed problematic typing in `cudf`
3. Added java jre for h20 lib

Fix broken docker build

---

Dockerfile.tmpl

Background:
DLVM base image includes curl/libcurl 7.68
mamba requires libcurl >= 7.86
this caused libcurl to be upgraded to 8.2.1 (latest) and the curl tool still uses the old version causing the mismatch warning.
Solution:
Upgrade curl/libcurl before installing mamba to version
This is installing the following curl/libcurl version:
```
curl               pkgs/main/linux-64::curl-8.2.1-hdbd6064_0
libcurl            pkgs/main/linux-64::libcurl-8.2.1-h251f7ec_0
```
http://b/299991198

Install newer versions of curl/libcurl

---

Dockerfile.tmpl

A new version of tensorflowjs has been released and requires tensorflow
>= 2.13. We are currently using 2.12 and this is causing a test failure.
Full context in bug.
http://b/300552705

Pin tensorflowjs

---

tpu/Dockerfile
tpu/config.txt

This will make it easier to change the python version across the whole Dockerfile. We will use py3.10 when possible.
http://b/295050179

Move python version to TPU config

---

Dockerfile.tmpl

eli5 will not import successfully with learntools 1.3 right now, pinning learntools back until these two are compatible
http://b/302136621

Fix eli5 import

---

tpu/Dockerfile
tpu/config.txt

Currently removing some packages which fail to install.
#1312 
http://b/295050179

Upgrade TPU VM to python 3.10

---

Dockerfile.tmpl

Upgrade pyarrow

---

Dockerfile.tmpl

Latest version fails with:
```
Traceback (most recent call last):
File "/input/tests/test_keras_cv.py", line 9, in test_inference
classifier = keras_cv.models.ImageClassifier.from_preset(
File "/opt/conda/lib/python3.10/site-packages/keras_cv/src/models/task.py", line 196, in from_preset
return super(cls, calling_cls).from_preset(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/keras_cv/src/models/task.py", line 147, in from_preset
model = cls.from_config({**config, **kwargs})
File "/opt/conda/lib/python3.10/site-packages/keras_cv/src/models/task.py", line 54, in from_config
config["backbone"] = keras.layers.deserialize(config["backbone"])
File "/opt/conda/lib/python3.10/site-packages/keras_core/src/layers/__init__.py", line 161, in deserialize
obj = …
```

Pin keras-cv

---

patches/log.py

Fixes #1324.
We setup a custom logger for Kaggle kernels.
Some of this logic could be simplified now that we are using Python 3.8+. I filed b/312963888 for this.
b/312961350

Add missing io import in log.py

---

patches/kaggle_secrets.py

User accounts credentials are no longer supported by `gsutil`. The recommendation is to use `gcloud storage` instead. See full details in bug.
We will add a script tip in the notebook editor to tell users using `gsutil` to use `gcloud storage` instead.
http://b/313996272

Do not set gsutil credentials.

---

Dockerfile.tmpl

This was pinned due to a python version mismatch, this has since been fixed in the newest version

unpin kaggle-environments

---

patches/sitecustomize.py
tests/test_google_generativeai_patch.py
tests/test_google_generativeai_patch_disabled.py

Use a new KAGGLE_GRPC_DATA_PROXY_URL env variable for gRPC proxying

---

patches/kaggle_module_resolver.py
tests/test_kaggle_module_resolver.py

Use kagglehub inside Kaggle Notebook for tensorflow_hub
Currently, if you try using tensorflow_hub with a kaggle.com URL inside
a Kaggle notebook but the model isn't attached you would get an error
message telling you to attach the model.
With this change, we are calling `kagglehub` instead and will attach the
model for the user if it is missing.
http://b/311184735

Use kagglehub inside Kaggle Notebook for tensorflow_hub

---

Dockerfile.tmpl

The latest version of KerasCV (0.8) and KerasNLP (0.7) now include the Kaggle integration.

Upgrade KerasCV & KerasNLP

---

Jenkinsfile
patches/kaggle_module_resolver.py

[b/319516798](http://b/319516798)
**Drive by change**: replace `/` with `-` in docker image tags that are based on `GIT_BRANCH`. `/` in tags are unsupported and caused some integration tests to fail.

fix(tfhub): check for user secrets token in kaggle_module_resolver

---

Dockerfile.tmpl

Adding Cuda home environment values helps other libraries avoid unwanted errors, for examples PyTorch and DeepSpeed.
PyTorch and DeepSpeed is just libraries I want to use as examples, ref: 
- https://github.com/microsoft/DeepSpeed/blob/master/op_builder/cpu/cpu_adam.py#L9
- https://github.com/pytorch/pytorch/blob/main/torch/utils/cpp_extension.py#L92, https://pytorch.org/docs/stable/_modules/torch/utils/cpp_extension.html#CppExtension
Please review my PR, thanks for all, @rosbo @djherbis

Resolves bugs and better supports Cuda libraries like PyTorch and DeepSpeed

---

tpu/config.txt

Also bump ecosystem packages (`torchtext`, `torchvision`, `torchaudio`) to latest versions

Bump PyTorch version to 2.2

---

Dockerfile.tmpl

so sklearn 1.3 and 1.4 came out since last docker update. broke learn tools, pinning and adjusting seems to fix the issues
also added dask-expr since it now a requirement of dask, unit test fail without it
tested learntool test locally
https://b.corp.google.com/issues/329274574

Fix learntools by pinning sklearn

---

Dockerfile.tmpl

yeah, perfect timing "sarcastic" tfdf now is at 1.9.x, which requires tf 2.16.
breaks units test. let's pin it
also looks like default-jre requires an "apt get  update" to install, lmk if this is an illegal move. without says cannot be found.

pin tfdf new ver. not comp

---

Dockerfile.tmpl
tests/test_pyfasttext.py

Package listed here have very little usage and/or deprecated. This is part of a bigger image reduction effort. lets test the water by removing these first
b/329273292
list of packages to be deleted:
orderedmultidict
smhasher
delorean
fbpca
pyfasttext
cysignals
marisa-trie

Unused Package Removal pt 1

---

Dockerfile.tmpl

keras 3.11.something moved from optree to dm-tre. other keras-related packages still need optree
add package, tested locally seems to pass smoke test. 
cc: @lucyhe

add optree

---

Dockerfile.tmpl
tests/test_hf_datasets.py

unpin datasets, looks like an attempt was made to do this in past but failed due to tfjs
but we don't install that package anymore. so let's unpin it since breaking due to package conflicts
moved s3fs to get a compatible version with fsspec. directly installed gcsfs, this is indirectly installed by another package but complains about fsspec version. installing directly seems to do the trick.
manually tested load_dataset function, works! 
https://github.com/Kaggle/docker-python/pull/1343
b/232247930

fix datasets

---

patches/kaggle_module_resolver.py
tests/test_kaggle_module_resolver.py

This change is required to unblock https://github.com/Kaggle/kaggleazure/pull/28591, which updates the Kernel MT to only use short URLs. 
**Testing**
Added unit test and ran ./test

[b/331681978] Add Short URL matching to KaggleFileResolver

---

Dockerfile.tmpl

LSP was broken in the release on 2024-03-20 by an automatic upgrade of jupyter_server from 2.12.5 to 2.13.0. Pinning this for now to resolve that issue.
http://b/333854354

Fix LSP by pinning jupyter_server.

---

tpu/config.txt

Also bump ecosystem packages (torchtext, torchvision, torchaudio) to latest versions
cc @will-cromar

Bump PyTorch version to 2.3

---

tpu/Dockerfile
tpu/config.txt

It looks like it was actually the JAX version bump that was breaking things, so trying the TF & Keras bump.

Trying Keras 3 w/ tf2.16 again

---

Jenkinsfile

There are no tests for the TPU image so promoting from :ci-pretest to :staging incorrectly makes it sound like the image is ready for the next stage of tests. Instead we'll leave it at :ci-pretest and have a separate process test and promote them.
http://b/336842777

Stop auto-promoting TPU image to staging tag

---

Jenkinsfile

Use new Artifact Registry cleanup policies feature instead.
http://b/321030221

Do not delete old unversioned images in Jenkins

---

Dockerfile.tmpl

looks like newer version of keras-nlp (>0.9.3) starts requesting "task.json" files when downloading models from kaggle-hub, which we don't provide afaik: https://screenshot.googleplex.com/BQpNeHjdS6yPnrm
which causes the docker keras-nlp test to fail (added logs):
https://paste.googleplex.com/4613448323563520
let's pin to unblock pipeline, reachout to models/kaggle hub poc about issue
https://b.corp.google.com/issues/341360061

Pin keras nlp

---

Dockerfile.tmpl
tests/common.py
tests/test_cudf.py
tests/test_cuml.py
tests/test_datashader.py
tests/test_geoviews.py

upgrade RAPIDS to 24.4.x (cuML and cuDF).
- looks like installing via mamba was not working, installed using conda with mamba package solver (which is faster than plan conda).
- Added test for cuML and cuDF, these packages were reported as "broken" for last the 6 months.
- Skip certain test if running on a p100 gpu
Going forward, rapids will not be compatible with p100 GPUs, that's a problem for another day
https://chat.kaggle.net/kaggle/pl/85tczsc4w3nhijkd1ftryxr7yo
b/296444923
b/341938540

Upgrade cuML and cuDF

---

Dockerfile.tmpl
tests/utils/kagglehub.py

wrongly pinned keras-nlp, let's unpinned it. update mock to support optional files.
https://b.corp.google.com/issues/341982731

Update Kagglehub mock and unpin keras-nlp

---

Dockerfile.tmpl

Seems like we get files containing pip output, unlikely that these are important. adding " " removes the file, which is convention syntax.
before:
https://screenshot.googleplex.com/9iVBh5Mtprsc95u
after: 
https://screenshot.googleplex.com/C6Kzxj8d8PqpCCS
fixes
https://github.com/Kaggle/docker-python/issues/1249

Remove "Rubbish" files in Root dir

---

Dockerfile.tmpl

We seem to be downloading multiple aiohttp version, we which is causing pip error out when installing some packages. we will remove and install again. 
added small refactor
proof of concept:
https://screencast.googleplex.com/cast/NDkzOTIxMTcwNTY3OTg3Mnw2Zjc5MjBkYy0wYg

Remove duplicate aiohttp

---

Dockerfile.tmpl
tests/test_xgboost.py

Yeah graphviz where's it at doesn't want to be installed. But moving it around helps get it installed

Move graphviz install around

---

Dockerfile.tmpl
tests/test_geopandas.py

This should fix the failing learn tools test.

fix geopandas again

---

Dockerfile.tmpl
tests/test_polars.py

Recreate of https://github.com/Kaggle/docker-python/pull/1424 which got borked
This is a plotting library required to do plotting actions from the popular `polars` library.

Add hvplot

---

Dockerfile.tmpl

looks like hvplot isnt needed anymore with newest polars release. 
let remove it from docker image

Remove hvplot

---

Dockerfile.tmpl
tests/test_fastai.py
tests/test_numpy.py

numpy 2.0 and greater is causing issues with handful of packages

Fix build due to numpy

---

Dockerfile.tmpl

Migrate to micromamba

---

Dockerfile.tmpl
tests/test_kagglehub.py

fixing main build.
- kagglehub login changes required updating our tests
- latest matplotlib is needed by handful of package, but breaks learntools. i provided a workaround

Fix Kagglehub test and Remove multiple version matplotlib files

---

Dockerfile.tmpl
kaggle_requirements.txt

These were unpinned during the base image migration but caused learntools to fail.
http://b/365782129

Re-pin learntools related packages.

---

Jenkinsfile

This speeds up e2e pipeline time since all three builds take around 10-11m now and tests take about 5m, making those two phases faster.

Split build and test parallel steps

---

kaggle_requirements.txt

Was failing tests with "Loading a dataset cached in a LocalFileSystem is not supported"

Fix old version of hf datasets

---

tpu/Dockerfile

I'm seeing it randomly pick the CUDA enabled version for some reason.
Trying a force reinstall while maintaining existing packages to see if that helps.

Try to make tf 2.18 on tpu vm install reliably

---

Dockerfile.tmpl
kaggle_requirements.txt

UV requires a separate flag for allowing prerelease packages to be installed.
kagglehub install fails due to this, since sigstore (a dependency) needs a prerelease package.
let's install it separate to allow prerelease installs.
https://b.corp.google.com/issues/394382016

Fix kagglehub 

---

Dockerfile.tmpl
kaggle_requirements.txt

Torch and Cuml have compatibility issues, installing them outside of requirements files removes some of our pins. Let's add them back in when installing to ensure that pins are in place.

Adjust pins to fix learn tools tests errors 

---

kaggle_requirements.txt
tests/test_transformers.py

We fix tests to adjust for deprecated methods, we added a line to ensure we get the latest transformers package is latest.

Ensure transformers is up to date

---

tpu/Dockerfile
tpu/config.txt
tpu/requirements.txt

Since the latest colab image is now python 3.11, we should try to bump this as well.
Also removing comments and code that are out of date

TPU upgrades to tf and torch, clean up dead code

---

Dockerfile.tmpl

Remove command to install uv as it is installed in the Colab base image. Remove updating cuda path as Colab base image sets the CUDA version

Remove command to set cuda path and install uv

---

config.txt

let's bump the image, this was released a couple days ago. while we were planning a release with the prior Base image, let's save us a release and get our self to the latest

Bump Colab Base Image - July

---

tpu/Dockerfile
tpu/config.txt
tpu/requirements.txt

Python 3.10 is entering its [last year of support](https://devguide.python.org/versions/) before end-of-life and many packages, including [NumPy](https://devguide.python.org/versions/), have dropped support for it altogether.
Included in this change:
* Upgrade the TPU docker image to derive from `python:3.11`.
* Upgrade `tensorflow` to 2.20.0.
* Upgrade `jax` to >=0.5.2. For a compatible dep closure, this installs `jax` 0.7.2 re: `tensorflow-tpu` dep on`libtpu`.
* Upgrade `torch` (and ecosystem) to 2.8.0. Of note, there is no wheel with a `+libtpu` label.
* Remove unneeded environment variable.
Tested:
Locally, by invoking `./tpu/build`:
> <img width="1116" height="297" alt="9jyLVT6hAPjKaCh" src="https://github.com/user-attachments/assets/e1c8e37e-5e65-4f43-807f-4ffca8d6b6ac" />
Also …

Upgrade TPU image to Python 3.11.Tpupy311

---

Dockerfile.tmpl
kaggle_requirements.txt
tests/test_fastai.py

The CPU/GPU container image builds are currently broken due to dependency resolution failures:
It appears, this version was removed from the Nvidia index since the last build.
We ensure that a compatible package version `libucx-cu12==1.18.1` is available by including the default PyPI and specifying an appropriate [index strategy](https://docs.astral.sh/uv/concepts/indexes/#searching-across-multiple-indexes) to `uv`.
In the near future, we may want to consider upgrading `cuml-cu12` and ecosystem to 25.6 or later.

Include the default PyPI for missing libucx-cu12 package version.
