Dockerfile

Requested by keras author.  
Build is tested and works locally.

Add keras library

---

Dockerfile

Reverts Kaggle/docker-python#2

Revert "Add keras library"

---

Dockerfile

Reverts Kaggle/docker-python#3

Revert "Revert "Add keras library""

---

Dockerfile

Added `igraph` for graph visualization. Fixed command bug in earlier pull request.

Add python-igraph package for graph visualization.

---

Dockerfile

Deep learning library featuring a higher-level API for TensorFlow. http://tflearn.org

Add a higher level api for TensorFlow

---

Dockerfile

Allowing interactive visualization in IPython notebooks.

Added plotly package

---

Dockerfile

* The `missingno` package is nice to explore missing data. 
Example: 
```
import missingno as msno
msno.matrix(your_df)
```
* The `pandas_profiling` package is nice for generating data reports (% of missing values, correlated variables, 
types of variables, histograms...)
Example: 
```
import pandas_profiling as pdp
pdp.ProfileReport(your_df)
```

Add two Python packages for data exploration

---

Dockerfile

deleting various temporary/source files and clean up cache

Reduce the size of the final docker image

---

Dockerfile

Adds pyLDAvis package from https://github.com/bmabey/pyLDAvis to the Dockerfile

Add pyLDAvis and pattern

---

Dockerfile

added two python modules for the Dstl challenge (https://www.kaggle.com/c/dstl-satellite-imagery-feature-detection).  One for reading tiff files and one for dealing with wkt geometries.  Looks like my text editor also removed a white space character from line 14.

pip install tifffile and descartes

---

Dockerfile

This enables the usage of advanced imputation functions like MICE and KNN.

Update Dockerfile with fancyimpute module

---

Dockerfile

Adding p7zip-full for extracting files from 7z archives (needed for DSB2017)

Adding p7zip tool for extracting files

---

Dockerfile

This package provides some tools to deal with `.ods` files (LibreOffice/OpenOffice).

Added a new dependency: `pyexcel-ods`

---

Dockerfile

Stemming is a useful tool for text preprocessing, and would be nice to have available in the kernels notebook

Add the stemming library to the docker file

---

Dockerfile

adding nibabel for reading nifti images (https://github.com/Kaggle/docker-python/issues/76)

Adding nibabel for medical images

---

Dockerfile

[Speedml package](https://speedml.com) provides quick start wrappers for popular packages in an easy, linear, intuitive machine learning workflow including components for EDA, feature engineering, model evaluation, hyper-parameters tuning, and feature selection.

Add speedml package

---

Dockerfile

ML-Ensemble is a library for ensemble learning with a Scikit-learn API. http://mlens.readthedocs.io/en/latest/

install mlens

---

Dockerfile

scikit-multilearn - A nice package for multilabel ML problems 
Web page: http://scikit.ml/api/index.html

Add scikit-multilearn for multilabel ML

---

Dockerfile

Adding CatBoost package, an open source machine learning library based on gradient boosting developed by Yandex

added catboost package

---

Dockerfile

Hello ! 
I would like to add a package I have developed for auto-ML. I have already tested it on several Kaggle competitions and it works well :) 
--> github: https://github.com/AxeldeRomblay/MLBox
--> my Kaggle profile: https://www.kaggle.com/axelderomblay
--> PyPI : https://pypi.python.org/pypi/mlbox
Then I would like to write a kernel tuto on this competition: https://www.kaggle.com/c/nyc-taxi-trip-duration/discussion
Thank you !

Add "MLBox" python package

---

Dockerfile

folium package

---

Dockerfile

Adds https://github.com/reiinakano/scikit-plot for easy visualization

Add scikit-plot

---

Dockerfile

plotnine is an implementation of a grammar of graphics in Python, it is based on ggplot2

add plotnine package

---

Dockerfile

[tensorpack](https://github.com/ppwwyyxx/tensorpack) *A neural net training interface based on TensorFlow.*
- setuptools is updated due to tensorpack's requirement `setuptools > 30`

* Update setuptools to the latest and add tensorpack framework

---

Dockerfile

I would like to use this module in my Titanic solution.

Add ethnicolr package for predicting ethnicity

---

Dockerfile

Useful for data visualization 
[Google PAIR-code Facets](https://github.com/pair-code/facets)

Add Google PAIR-code Facets

---

Dockerfile

Adds [`geoplot`](https://github.com/ResidentMario/geoplot), a high-level `cartopy` wrapper. All the prereqs are already in the image.

Add geoplot

---

Dockerfile

edward library

---

Dockerfile

Two packages for handling countries' names, subdivisions, languages, currencies, and their different ISO codes. It would be quite useful, used in association with other packages for text analysis and map visualization. Use case example: extracting geographical named entities from a text, converting them to their ISO codes, and plotting them on a map.
https://pypi.python.org/pypi/pycountry
https://pypi.python.org/pypi/iso3166

adding pycountry and iso3166

---

test_build.py

simply add plotly and ggplot to the test_build

add some visualization tools 

---

Dockerfile

Method for oversampling imbalanced data complying with the imbalanced-learn API: https://github.com/felix-last/kmeans_smote

Add kmeans-smote

---

Dockerfile

Fast Python Collaborative Filtering for Implicit Datasets
This project provides fast Python implementations of the algorithms described in the paper Collaborative Filtering for Implicit Feedback Datasets and in Applications of the Conjugate Gradient Method for Implicit Feedback Collaborative Filtering.
http://implicit.readthedocs.io/en/latest/index.html

Add implicit

---

Dockerfile

Update Dockerfile (pip install vtk)

---

Dockerfile

Please update dockerfile so that we can use fastai library for kaggle kernels. Thanks 
It's available from pip install now.
Fast.ai is deep learning and machine learning library which is developed by Jeremy Howard (and contributors). This library already has wide acceptance by people practicing deep learning and it recently came out on PyPi, especially for people who want to use it for kaggle kernels.

Update Dockerfile (fastai)

---

Dockerfile

Lime is a package dedicated to model explanations developped by H2Oai. Very helpful to understand decisions made by a gradient boosting.
https://github.com/marcotcr/lime

adding lime package

---

Dockerfile

pip install pronouncing && \
pip install markovify && \
both are useful for natural language processing applications

Update Dockerfile - install pronouncing and markovify

---

Dockerfile

Scattertext produces interactive visualizations showing how BoW features differ among categorized documents. This can be very useful in exploring text classification tasks.  It can also be used for visualizing categorical feature importance scores.

Update Dockerfile to install scattertext

---

Dockerfile

ortools is the Python wrapper for the Google Optimization Tools: https://developers.google.com/optimization/

Add pip install ortools in Dockerfile

---

Dockerfile

Janome (蛇の目) is a Japanese morphological analysis engine (tokenizer, pos-tagger) including built-in dictionary and language model.

Add Janome

---

Dockerfile

More info on https://pypi.python.org/pypi/emoji/

add emoji package

---

Dockerfile

Nilearn: Machine learning for NeuroImaging in Python

pip install nilearn

---

Dockerfile

This was tested on the docker image following instructions from the README. Featuretools is a library for feature engineering that is compatible with pandas and sklearn. Here's the [website](https://www.featuretools.com/) and [github repo](https://github.com/Featuretools/featuretools).

pip install featuretools

---

Dockerfile

adding code to install Keras RCNN (https://github.com/Kaggle/docker-python/issues/172)

Adding Keras RCNN

---

Dockerfile

[mlcrate](https://github.com/mxbi/mlcrate) is a package I've been working on recently, essentially a collection of tools for ML - Mainly focused specifically on kaggle actually. :)
I tested this with the latest kaggle docker, didn't run into any issues.

Add mlcrate

---

Dockerfile

This class implements the permutation importance metric for random forests

pip install rf_perm_feat_import

---

Dockerfile

Added pip install for BigQuery_Helper: https://github.com/SohierDane/BigQuery_Helper

Add bq_helper

---

Dockerfile

Reference: https://pypi.python.org/pypi/pyupset/0.1.1.post1

Added pyupset package

---

Dockerfile

adding scikit-optimize dependency for more intelligent parameter and hyperparameter optimization, resolving https://github.com/Kaggle/docker-python/issues/174

Adding scikit-optimize

---

Dockerfile

hyperopt-sklearn simplifies Hyperopt hyperparameter optimization for sklearn tools.

Add support for hyperopt-sklearn

---

Dockerfile

adding keras-tqdm

---

Dockerfile
test_build.py

As suggested in MLWave/kepler-mapper#40.
Kepler Mapper provides an implementation of the Mapper algorithm from Topological Data Analysis. It can be used for high dimensional data visualization and feature engineering.

Include Kepler Mapper

---

Dockerfile
kaggle_tools_update.Dockerfile
patches/entrypoint.sh

This PR is to fix https://b.corp.google.com/issues/111795349 to direct pip to install third-party libraries in a designated writeable directory.

Add ENTRYPOINT script to initialize the image.

---

Dockerfile

BUG=https://buganizer.corp.google.com/issues/112953325

pin notebook package to 5.5.0 to fix styling issue

---

tests/test_gensim.py

add tests for gensim

---

Dockerfile

Already being installed here: https://github.com/Kaggle/docker-python/blob/master/Dockerfile#L441

Remove duplicate install for opencv

---

Dockerfile

Duplicated at: https://github.com/Kaggle/docker-python/blob/master/Dockerfile#L447

Remove duplicate install for Pillow

---

Dockerfile

already being install at line 20.

Remove duplicate install of seaborn

---

Dockerfile

See this issue for more context: https://github.com/matplotlib/basemap/issues/424

Fix compatibility issue with matplotlib and basemap

---

Dockerfile

Remove the duplicate pip install for matplotlib

Pin matplotlib to prevent compatibility issue with basemap

---

Dockerfile

We already have tests for the sklearn

install scikit-learn from pip

---

Dockerfile
tests/test_datashader.py

Part of an effort to use only one package manager.

install datashader from pip and add tests

---

Dockerfile
tests/test_vtk.py

Add libGL1 to satisfy vtk dependencies

---

Dockerfile
tests/test_seaborn.py

Also added a test to prevent downgrading to an older version.

Install latest version of seaborn

---

Dockerfile
tests/test_rgf.py

See #238
cc/ @fukatani @StrikerRUS

Add RGF package

---

Jenkinsfile
diff

Shows a diff like this:
```
== Comparing dpkg-query --show -f "${Package}==${Version}\n" ==
No diff
== Comparing pip freeze ==
bokeh==1.0.1						      |	bokeh==1.0.2
boto3==1.9.52						      |	boto3==1.9.57
botocore==1.12.52					      |	botocore==1.12.57
-e git+https://github.com/SohierDane/BigQuery_Helper@8615a7f6 |	bq-helper==0.4.1
-e git+http://github.com/tensorflow/cleverhans.git@8942beadba |	cleverhans==3.0.1
dask==0.20.2						      |	dask==1.0.0
distributed==1.24.2					      |	distributed==1.25.0
featuretools==0.4.0					      |	featuretools==0.4.1
google-api-python-client==1.7.4				      |	google-api-python-client==1.7.5
mkl-fft==1.0.6						      |	mkl-fft==1.0.9
msgpack==0.5.6						      |	msgpack==0.6.0
>	nervananeon==2.6.0
ortools==6.9.5824					      |	ortools==6.10.6025
> …
```

Show package versions diff in the docker build pipeline

---

Dockerfile

See: https://github.com/facebook/prophet/issues/775

Pin fbprophet to 0.3post2 version

---

Jenkinsfile

Only on Monday and Wednesday. We don't get much value from more.

Cron trigger Jenkins pipeline less frequently

---

patches/sitecustomize.py

Remove tensorflow preloading

---

Dockerfile
tests/test_tsfresh.py

Add tsfresh

---

Dockerfile

See comment in code for details.

Pin flake8 to a specific version

---

Dockerfile

Keep pandas to version compatible with tsfresh

---

tests/test_user_secrets.py

This fixes the failures in CI now.

Update test_user_secrets to expect a POST request instead of GET.

---

gpu.Dockerfile

prevent mxnet from downgrading numpy

---

Dockerfile

Also removes the version pin for matplotlib.
https://b.corp.google.com/issues/128333086

Fix errors with basemap/matplotlib

---

tensorflow-whl/Dockerfile

Same change than for the `gpu.Dockerfile` in #469.

TF whl: Remove pin for keras_(applications|preprocessing)

---

Dockerfile

Set PROJ_LIB to point to the proj4 library

---

Dockerfile
tests/test_chainercv.py

Please add chainercv.
chainercv is a Library for Deep Learning in Computer Vision, useful in kaggle competition with image.
- https://github.com/chainer/chainercv

Add chainercv

---

clean-layer.sh

As part of the cleanup procedure

Ensures the current working directory won't be deleted

---

Dockerfile

This command has been added to the `clean-layer.sh` script in #527

Remove cd command now done in clean-layer

---

Dockerfile

https://www.kaggle.com/product-feedback/29329#513221

Do not pin fbprophet

---

Dockerfile
tests/test_albumentations.py

Hi! 
I added the best library for image augmentations: [albumentations](https://github.com/albu/albumentations).
It was created by top-kagglers and will be useful in kaggle-kernels.

Add albumentations library

---

Dockerfile
tests/test_allennlp.py

This PR fixes the PR #524 by @RyujiTamaki. There was a conflict for a package, it was solved by upgrading anaconda3 to 5.3.0

add allennlp package

---

Dockerfile

https://github.com/Kaggle/docker-python/issues/548

Do not install allennlp dependencies until conflict is resolved

---

Dockerfile
gpu.Dockerfile
tests/test_fasttext.py

Build + Test work on CPU, still awaiting GPU results.

Fixes build by updating Anaconda and fastText->fasttext

---

Dockerfile
gpu.Dockerfile
tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile

Upgrade to TensorFlow 1.14

---

patches/sitecustomize.py

Doesn't change modules imported, but just cleaning up.

Remove unnecessary imports.

---

Dockerfile
tests/test_automl.py

b/138459233 - add google-cloud-automl python to `docker-python`.

Add google-cloud-automl

---

Dockerfile
tests/test_geopandas.py

fix for this issue: https://www.kaggle.com/product-feedback/53008
BUG=118703729

geopandas - for spatial join

---

patches/kaggle_secrets.py
tests/test_user_secrets.py

Add get_secret() api to kaggle_secrets.

---

Dockerfile

Revert pinning pytorch/audio now that the build problems have been fixed

---

Dockerfile

Pin ImageMagick

---

Dockerfile
gpu.Dockerfile
tests/test_keras.py
tests/test_tensorflow.py

* Installed TensorFlow 2.0 for the CPU and GPU image
* Fixed `test_tensorflow.py` to use the new TF 2.0 api and be TF 2.0 idiomatic

Upgrade to TensorFlow 2.0

---

Dockerfile

See https://github.com/ipython/ipykernel/issues/422
Testing performed and outcome in b/143058491
BUG=143058491

Pin ipykernel to 5.1.1

---

Dockerfile

Fix tensorflow-version Docker LABEL

---

Dockerfile
gpu.Dockerfile

Updated pytorch conda package name for cpu version

---

Dockerfile

Pin pyproj to fix METADATA issue

---

Dockerfile
tests/test_gcloud.py

Pin rtree to fix gcloud test failure.

---

Dockerfile

Pin osmx to avoid rtree upgrade

---

Jenkinsfile

Fix a race causing the tests to be run against the wrong image.

Avoid race between build in test

---

Dockerfile
tests/test_wandb.py

Hi folks!
This is an updated PR:
- adding the package wandb
- adding a test for wandb
- implementing the changes requested [here](https://github.com/Kaggle/docker-python/pull/599).
Cheers!

Add wandb package

---

gpu.Dockerfile
tests/test_jax.py

Fixes #679 
cc/ @marketneutral

Add JAX package

---

gpu.Dockerfile

Fix test failure:
```
ValueError: jaxlib is version 0.1.36, but this version of jax requires version 0.1.37.
```
BUG=147245673

Install latest version of jaxlib

---

Dockerfile
gpu.Dockerfile

Use TensorFlow 2.1.0-rc2

---

Dockerfile
gpu.Dockerfile

Install TensorFlow 2.1.0 GA whl

---

gpu.Dockerfile

Required by LightGBM (w/ GPU support).
BUG=118296887

Install OpenCL

---

Dockerfile

Needed for upcoming RL learn course.

Install kaggle-environments

---

patches/kaggle_gcp.py

Resolves errors in [b/148144131](http://b/148144131)

Use the newer google.api_core.gapic_v1.client_info.ClientInfo

---

Dockerfile
gpu.Dockerfile

The latest version of pip is causing issue when trying to install mxnet. See https://github.com/pypa/pip/issues/7626
BUG=148097039

Pin pip version to 19.3.1

---

Dockerfile

Pin holidays package to version compatible with fbprophet

---

gpu.Dockerfile

Similar to nvidia-smi but for OpenCL.

Add clinfo tool

---

Dockerfile

Pin geopandas & vowpalwabbit

---

README.md

[markdownlint](https://github.com/markdownlint/markdownlint)

Update README.md according to markdownlint

---

Dockerfile
gpu.Dockerfile
tests/test_nnabla.py

Add Sony's [NNabla](https://nnabla.org) packages including the CUDA extension. NNabla is a high-performance deep learning library (more than 2.3k stars). I've also added the unit test. It would be great if this is installed as a standard library.
Thank you.

Add nnabla

---

Dockerfile
README.md
gpu.Dockerfile
tests/test_nnabla.py

The dependent packages should support 1.0 now.

unpin pandas #723

---

Dockerfile

- Fix/simplify h2o installation
- Install the safitty package used in the catalyst test

Fix test failures: h2o & catalyst

---

Dockerfile

Few GitHub stars. No usage.
BUG=152539178

Remove raccoon package

---

Dockerfile

Unmaintained (last release was 2017). No usage.
BUG=https://buganizer.corp.google.com/issues/152539178

Remove speedml package

---

Dockerfile

When using `pip` alongside `conda`. It is recommended to run all the `conda` commands first and then install the remaining packages with pip: https://www.anaconda.com/using-pip-in-a-conda-environment
BUG=152629236

Install conda packages first

---

README.md

We released our GPU images publicly on 4/7/2020

Update README to include public GPU repo.

---

tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile

Build TensorFlow wheel for Python 3.7

---

Dockerfile
gpu.Dockerfile

Use the new wheel built in #772

Use dlvm TensorFlow whl

---

tests/data/notebook.ipynb
tests/test_jupyter_nbconvert.py

Add nbconvert test

---

Dockerfile
gpu.Dockerfile

Latest version is causing our GPU tests to hang and fail with a CUDA memory error. See linked bug for all details.
BUG=154150582

Pin JAX and jaxlib

---

Dockerfile
tests/test_imports.py

Update the version of python-tensorflow-whl used in the build and install tensorflow-gcs-config from the wheel.
http://b/152051681

Install tensorflow-gcs-config from the python-tensorflow-whl

---

tests/test_cupy.py

The package is working fine. This is simply to prevent future regression.

Add cupy tests

---

Dockerfile
tests/test_kornia.py

This PR includes Kornia: Computer VIsion Library for PyTorch in the docker image file.
The library is useful for people working with pytorch and computer vision, including most of the more common opencv functionalities in GPU and some accelerated data augmentation transformations.
More information about the project: https://kornia.org

add kornia to dockerfile

---

tests/test_pysal.py

Use new pysal package import after 2.0 upgrade

---

gpu.Dockerfile

See context in bug (includes internal links).
BUG=155202022

Fix nvidia-smi in notebook environment.

---

Dockerfile

Remove osmnx pin

---

Dockerfile

Adding ffmpeg, per [user request](https://www.kaggle.com/general/146035).

Adding ffmpeg

---

tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile
tensorflow-whl/tensorflow-gcs-config/tensorflow_gcs_config/gcs_config_op_kernels.cc

Build TensorFlow 2.2.0 whl

---

Dockerfile
gpu.Dockerfile

PR creating the TensorFlow 2.2.0 whl: #803
BUG=151627748

Use TensorFlow 2.2.0 wheels

---

Dockerfile

Install cloud-tpu-client package

---

Dockerfile
gpu.Dockerfile

This allows support for Custom Op. See https://github.com/tensorflow/addons#987
BUG=145555176

Use custom TFA wheels.

---

Jenkinsfile

This way, we avoid the risk of releasing a CPU and GPU image from 2 different builds.
BUG=157163453

Add staging tag to images at the end of build pipeline

---

Dockerfile
gpu.Dockerfile

See: https://github.com/Kaggle/docker-python/issues/791#issuecomment-632223272

Use consistent conda channels list.

---

Dockerfile
tests/test_keras_tuner.py

Also included a test to prevent regression.
BUG=157935320

Install keras-tuner

---

patches/kaggle_secrets.py
tests/test_user_secrets.py

https://b.corp.google.com/issues/158133824
Note: this won't actually work until the in-flight PRs make it to prod, but want to get this into the image so it can be deployed.

Add a UserSecrets.get_gcloud_credentials() method.

---

Dockerfile

Affecting startup latency.
BUG=156116184

Disable nb_conda

---

Dockerfile
tests/test_imports.py

This package do not include the datasets. It is merely a
nice interface to load curated dataset from GCS: https://www.tensorflow.org/datasets
BUG=158329670

Add tensorflow-datasets package

---

Dockerfile

Add imagecodecs

---

diff

- Use `dpkg`
- Add more diff like the operating system
Note: will copy to `docker-rstats` repo.

Improve diff

---

Dockerfile
tests/test_pydub.py

For the birdcall competition, per user requests like https://www.kaggle.com/c/birdsong-recognition/discussion/158880#888647

Added pydub

---

Dockerfile

pysal 2.2.0 has been released and use different path.
BUG=161473620

Fix import statement for pysal test

---

patches/kaggle_datasets.py
patches/kaggle_secrets.py
patches/kaggle_web_client.py
tests/test_datasets.py
tests/test_user_secrets.py

kaggle-web-client now has the logic to make necessary requests to the web-tier.
http://b/148309982

Use kaggle-web-client in kaggle_secrets.

---

Dockerfile
gpu.Dockerfile

PR creating the TensorFlow 2.3.0 whl: #857.
BUG=161805280

Use TensorFlow 2.3.0 wheels.

---

tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile

Next: 
- Use the new TensorFlow whl in our images.
BUG=161805280

Build TensorFlow 2.3.0 whl

---

tests/test_vowpalwabbit.py

Relax assertion in vowpalwabbit test.

---

Dockerfile

Pin tensorforce to prevent matplotlib upgrade

---

Dockerfile
gpu.Dockerfile
tests/test_fastai.py

Upgrade to Pytorch 1.6

---

Dockerfile
tests/test_pytorch_lightning.py

Hi, added [Pytorch Lightning](https://github.com/PyTorchLightning/pytorch-lightning/) - The lightweight PyTorch wrapper for high-performance AI research.
Lightning disentangles PyTorch code to decouple the science from the engineering by organizing it into 4 categories:
- Research code (the LightningModule).
- Engineering code (you delete, and is handled by the Trainer).
- Non-essential research code (logging, etc... this goes in Callbacks).
- Data (use PyTorch Dataloaders or organize them into a LightningDataModule).

Add pytorch-lightning to Dockerfile

---

tests/test_pytorch_lightning.py

Updated test with the changes from the recent release.

Update pytorch-lightning 1.0

---

tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile

Build TensorFlow 2.3.1 wheel.

---

Dockerfile
tests/test_tensorflow_cloud.py

Add TensorFlow Cloud

---

gpu.Dockerfile

Install Rapids cuDF & cuML libraries.

---

tests/test_rapids.py

Add tests for cuml & cudf to prevent regression.

---

Dockerfile
gpu.Dockerfile

Upgrade to PyTorch 1.7

---

gpu.Dockerfile

Upgrade JAX to 0.2.6

---

tests/test_xgboost.py

Add xgboost version regression test.

---

Dockerfile
gpu.Dockerfile

Use TensorFlow 2.4.0 wheels.

---

tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile

Bump TensorFlow addons to 0.12 (supports TF 2.4).
BUG=172352589

Build TensorFlow 2.4.0 whl

---

Jenkinsfile

Post jenkins updates to Mattermost

---

Dockerfile
Jenkinsfile

By pinning theano-pymc version.
I was not able to fix the test itself.
http://b/178107003

Fix theano test

---

tests/test_xgboost.py

- Add assertion.
- Stopped using deprecated label encoder (removes the following warning: https://paste.googleplex.com/6273615185051648)

Improve xgboost test

---

Dockerfile
gpu.Dockerfile

Use new TF 2.4.1 whl

---

Jenkinsfile

Starts 3 hours before the SDG daily build: https://github.com/Kaggle/shared-docker-graph-builder/blob/490eff4a2b34a22837a9a32df9c90733f562ce6d/Jenkinsfile#L4

Schedule build every day of the week.

---

Dockerfile
patches/kaggle_gcp.py
test
tests/test_ucaip.py

Allow users to use the aiplatform.Datasets and aiplatform.CustomTrainingJob packages

Add integrations for ucaip

---

tensorflow-whl/CHANGELOG.md
tensorflow-whl/Dockerfile

Build CUDA 11 TensorFlow wheels

---

Dockerfile
gpu.Dockerfile

Upgrade to CUDA 11.0

---

gpu.Dockerfile

The latest version is causing an issue with nnabla. nnabla fixed the
issue, pinning while waiting for new version of nnabla:
https://github.com/sony/nnabla/issues/892
http://b/190622765

Pin pynvml

---

Dockerfile
tensorflow-whl/Dockerfile

Upgrade base image to m71

---

Dockerfile

Forgot to upgrade the CPU Dockerfile in #1039

Upgrade JAX on CPU image to match GPU image.

---

gpu.Dockerfile

Upgrade cudf/cuml libraries.

---

Dockerfile.tmpl
tests/test_vaex.py

Fixes #928. Original PR is #1031 (thanks @JovanVeljanoski)
- Includes a test.
http://b/191699352

Add vaex package.

---

README.md

- Refer to the new `Dockerfile.tmpl`
- Remove outdated documentation about GPU layers/
- Remove link to outdated external documentation.
Fixes #\<issue_number>

Refresh README documentation

---

Dockerfile.tmpl

Just updates `cudf` & `cuml` to the latest versions recently released.

Update cudf & cuml to 21.10

---

Jenkinsfile

Standardized with `docker-rcran`: https://github.com/Kaggle/docker-rcran/pull/57#discussion_r762150273

Delete unversioned images after 6 months

---

Dockerfile.tmpl

The issue seems to have been resolved: https://github.com/huggingface/transformers/issues/12904
so maybe now we can use latest versions of pytorch-lightning and torchmetrics. let's see if it works.
cc @rosbo

update pytorch-lightning to latest

---

tests/data/haarcascade_frontalface_alt.xml
tests/test_opencv.py

Add opencv classifier test

---

Dockerfile.tmpl

See: https://github.com/vaexio/vaex/issues/1817
http://b/214080882

Pin blake3 to fix vaex

---

Dockerfile.tmpl
tests/test_flax.py
tests/test_jax.py

- Added additional smoke tests for jax and flax.
http://215555626

Use CUDA 11.0 compatible JAX version.

---

Dockerfile.tmpl

Set KMP_SETTINGS to false to avoid Tensorflow warning message

---

Dockerfile.tmpl
tests/test_fbprophet.py

- The package has changed names: https://github.com/facebook/prophet#version-10-20210328

Upgrade to latest version of prophet (1.0.1)

---

Dockerfile.tmpl

Unpin torchmetrics version

---

Dockerfile.tmpl

Expose GIT_COMMIT & BUILD_DATE ARGs as ENV variables

---

tests/test_prophet.py

The new version of prophet (1.1) introduced breaking changes to the fit
arguments.
http://b/237327883

Fix prophet test

---

Dockerfile.tmpl
tests/test_openpyxl.py

Add openpyxl

---

Dockerfile.tmpl

Pin accelerate which breaks catalyst on 2xT4 GPUs

---

Jenkinsfile

This will verify that the unit tests pass on both GPU types.
http://b/254301311

Run GPU unit tests on T4x2

---

Dockerfile.tmpl

Pin scikit-learn-intelex as the newest version breaks

---

Dockerfile.tmpl

Pin google-api-core

---

Dockerfile.tmpl

We should always attach a bug so we understand in the future why that package is pinned.
http://b/266272046

Add a bug to the prophet pin

---

Dockerfile.tmpl
tests/test_torchinfo.py

Add torchinfo package to summarize a pytorch model

---

Dockerfile.tmpl

Fix bash printing a warning on all execs.

---

Dockerfile.tmpl
tests/test_tensorflowjs.py

Install tensorflowjs

---

Dockerfile.tmpl

Fix nbconvert slowdown

---

Dockerfile.tmpl

Unpin gensim

---

Dockerfile.tmpl

Install older version of boto3, because 1.26.103 is broken

---

Dockerfile.tmpl
tests/test_pycolmap.py

Install pycolmap for py3.10

---

Dockerfile.tmpl

Remove extra cupy installation

---

Dockerfile.tmpl

Upgrade JAX CUDA

---

Dockerfile.tmpl

Unpin prophet

---

Dockerfile.tmpl

http://b/212703016, http://b/284952059

unpin opencv-python

---

Dockerfile.tmpl
tests/test_keras_core.py
tests/test_kerascv.py

Fix: Install Keras core

---

Dockerfile.tmpl

Please see https://github.com/igraph/python-igraph/issues/699 for an explanation.

change python-igraph to igraph

---

Jenkinsfile

The goal is to retry any flaky test, and the T4 tests which setup seems to be flaky.

Add retry block for tests

---

tpu/Dockerfile

Single pip install for compatibility

---

tpu/Dockerfile

Fix numpy version

---

Jenkinsfile

https://buganizer.corp.google.com/issues/295375085

Remove commands for slack

---

tpu/Dockerfile

https://www.kaggle.com/code/wcromar/pytorch-xla-2-0-on-kaggle/notebook?scriptVersionId=124841632

Add TPU deps from PyTorch example

---

Dockerfile.tmpl

Install latest version of seaborn which fixes heatmap

---

patches/kaggle_secrets.py
tests/test_user_secrets.py

Fix UserSecretsClient#set_tensorflow_credentials

---

Dockerfile.tmpl
tests/test_keras_core.py

http://b/315458381
http://b/315753846

Fix keras & translate

---

tpu/Dockerfile
tpu/config.txt

Install Keras 3

---

Dockerfile.tmpl

Pin jax to fix tensorflowjs issue

---

Jenkinsfile

There seems to be an issue with GCR.
See bug for full context.
http://b/321030221

Disable old unversioned GPU Docker images

---

README.md

Added instructions to run specific test or against specific image

Update README.md to include additional ./test flags

---

tpu/config.txt

TPU VM tf2.16

---

tpu/Dockerfile

We should be able to install Keras 3 directly now that we have tf2.16.
http://b/318672157
http://b/334956594

Keras 3 w/ tf2.16

---

tpu/Dockerfile
tpu/config.txt

Reverts Kaggle/docker-python#1385
Reverts #1384
tf/libtpu combo is crashing, will have to wait to upgrade

Revert "Keras 3 w/ tf2.16"

---

Dockerfile.tmpl

Remove stale comment about keras-nlp pin

---

Dockerfile.tmpl

Update pillow to latest version so it can handle opening jpg images.

removed fixing pillow to 9.5.0

---

tpu/Dockerfile
tpu/requirements.txt

This should significantly improve build times for this image.
http://b/350047073

Build tpu image with uv

---

kaggle_requirements.txt
tests/test_cuml.py

Install cuml-cu12

---

kaggle_requirements.txt

Per @jplotts, I'll wait to merge this until after the holidays
http://b/379756505

Bump `kagglehub` and add optional deps

---

Dockerfile.tmpl

Add kagglehub optional signing features

---

kaggle_requirements.txt

Let's make sure that we install the latest version of kaggle in our image.
cc: @stevemessick

Update kaggle package
